<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa cái này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/thamdo/delete/pollsid/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ order: '<?php echo $count;?>', 
										polls_content: "<?php echo $item['polls_content'];?>",
										polls_status: "<?php if ($item['polls_status']==0) echo 'Câu hỏi'; else echo 'Câu trả lời';?>",
										polls_vote:	   "<?php echo $item['polls_vote'];?>",
										sua: 
											'<?php 
												echo '<a href="'.$this->baseUrl().'/admin/thamdo/edit/pollsid/'.$item['polls_id'].'" title="Edit"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
											?>',
										xoa: 
											'<?php
												echo '<a class="del_button" onclick="confirmDel('.$item['polls_id'].')" title="Del"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
											?>'
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'polls_content',
								label: 'Nội dung',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'polls_status',
								label: 'Thể loại',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'polls_vote',
								label: 'Lượt bình chọn',
								sortable:true,
								formatter: '<center>{value}</center>',
								allowHTML: true
							},
							
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							},
							{
								key: 'xoa',
								label:'<center>Xóa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link" style="float:right">
				<?php
				if($this->role=="0")
				{
				?>
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/thamdo/insert');?>">Thêm mới</a>
				<?php
				}
				?>
			</div>
				<div class="submit_link" style="float:left; font-weight: bold;">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>