<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script type="text/javascript">
	$(function() {
		setUpFCK('image_link',200,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
	});
</script>
<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
<script type="text/javascript">
$(document).ready(function() {
	var check = document.getElementById('is_active-1');
	check.checked = true;
});

</script>
					<?php if (isset($_SESSION['result']))
					{
						echo '<br/>';
						echo '<p class="message">';
						echo $_SESSION['result'];
						echo '</p>';
						unset($_SESSION['result']);
					}
					?>
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset class="fieldset">
					<label>Nội dung</label>
					<?php echo $this->form->getElement('polls_content');?>
				</fieldset>
				<fieldset class="fieldset">
					<label>Thể loại: Câu trả lời</label>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/thamdo">Hủy bỏ</a>
				<input type="submit" name="submit" value="Thêm mới" class="alt_btn">
			</div>
		</footer>
	</article>
</form>