<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Nội dung</label>
					<?php echo $this->form->getElement('comment_content');?>
				</fieldset>
				
				<fieldset>
					<label>Tin tức</label>
					<?php echo $this->form->getElement('news_id');?>
				</fieldset>
				<fieldset>
					<label>Người đọc</label>
					<?php echo $this->form->getElement('reader_id');?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>