<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script type="text/javascript">
	$(function() {
		setUpFCK('comment_content',200,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
	});
</script>
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Nội dung</label>
					<?php echo $this->form->getElement('comment_content');?>
				</fieldset>
				
				<fieldset>
					<label>Tin tức</label>
					<?php echo $this->form->getElement('news_id');?>
				</fieldset>
				<!--fieldset>
					<label>Người đọc</label>
					<?php echo $this->form->getElement('reader_id');?>
				</fieldset-->
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>