<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa bình luận này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/comment/del/comment_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<?php
	function word_limiter($str,$limit)
	{
		if (strlen($str)>$limit)
		{
		 	while ($str[$limit] != ' ')
		   	$limit++;
		}
		else $limit = strlen($str);
 		return substr($str, 0, $limit);
	}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>	
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
							<?php 
								$count=1;
								foreach ($this->list as $item)
								{
									?>
									{ 
										order: "<?php echo $count;?>", 
										comment_content: "<?php $content = str_replace(array("\n", "\r"), ' ', strip_tags(str_replace('"',"'",$item['comment_content'])));
														if(strlen($content) > 100)
															echo word_limiter($content, 100).' ...';	
														else echo word_limiter($content, 100);	?>",							
										news_id: "<?php 											
											$string = $this->listNewsTitle[($this->page-1)*25+$count-1];
											if(strlen($string) > 100)
												echo str_replace('"',"'",word_limiter($string, 100)).' ...';	
											else echo str_replace('"',"'",word_limiter($string, 100));
										 ?>",
										sua: "<?php echo $item['comment_id']?>",
										xoa: "<?php echo $item['comment_id']?>"
									},
							<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'comment_content',
								label: 'Nội dung bình luận',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'news_id',
								label: 'Tin tức',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center><a href="<?php echo $this->baseUrl();?>/admin/comment/edit/comment_id/{value}" title="Sửa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a></center>',
								allowHTML: true
							},
							{
								key: 'xoa',
								label:'<center>Xóa</center>',
								formatter: '<center><a class="del_button" onclick="confirmDel({value})" title="Xóa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a></center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<?php echo $this->paginationControl($this->list,
                                    'Sliding',
                                    'tintuc/pagination.phtml');?>
			</div>
		</footer>
	</div>
</article>