<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa bình luận này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/comment/del/comment_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<?php
	function word_limiter($str,$limit)
	{
		if (strlen($str)>$limit)
		{
		 	while ($str[$limit] != ' ')
		   	$limit++;
		}
		else $limit = strlen($str);
 		return substr($str, 0, $limit);
	}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
	$(document).ready(function() {
		$('#listnews').dataTable({
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
			"bProcessing": true,
	        "bServerSide": true,
	        "sAjaxSource": "<?php echo $this->baseUrl();?>/admin/comment/loaddata/viewtype/1"
		});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Nội dung bình luận</th>
				<th style="background:transparent">Tin tức</th>
				<th style="background:transparent">Sửa</th>
				<th style="background:transparent">Xóa</th>
			</thead>
			<tbody>
				<tr>
					<td colspan="5" class="dataTables_empty">Loading data from server</td>
				</tr>
			</tbody>
		</table>
		
		<footer>
			<div class="submit_link">
			</div>
		</footer>
	</div>
</article>