<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa bình luận này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/comment/del/comment_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<?php
	function word_limiter($str,$limit)
	{
		if (strlen($str)>$limit)
		{
		 	while ($str[$limit] != ' ')
		   	$limit++;
		}
		else $limit = strlen($str);
 		return substr($str, 0, $limit);
	}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
	$(document).ready(function() {
		$('#listnews').dataTable({
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25
		});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Thứ tự</th>
				<th>Nội dung bình luận</th>
				<th>Tin tức</th>
				<th style="background:transparent">Sửa</th>
				<th style="background:transparent">Xóa</th>
			</thead>
			<tbody>
				<?php 
				$count=1;
				foreach ($this->list as $item)
				{?>
					<tr>
						<td><?php echo $count;?></td>
						<td><?php $content = str_replace(array("\n", "\r"), ' ', strip_tags(str_replace('"',"'",$item['comment_content'])));
														if(strlen($content) > 100)
															echo word_limiter($content, 100).' ...';	
														else echo word_limiter($content, 100);	?></td>
						<td><?php $string = $this->listNewsTitle[$count-1];
											if(strlen($string) > 100)
												echo str_replace('"',"'",word_limiter($string, 100)).' ...';	
											else echo str_replace('"',"'",word_limiter($string, 100));
										 ?></td>
						<td><center><a href="<?php echo $this->baseUrl();?>/admin/comment/edit/comment_id/<?php echo $item['comment_id']?>" title="Sửa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a></center></td>
						<td><center><a class="del_button" onclick="confirmDel(<?php echo $item['comment_id']?>)" title="Xóa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a></center></td>
					</tr>
				<?php $count++; }?>
			</tbody>
		</table>
		
		<footer>
			<div class="submit_link">
			</div>
		</footer>
	</div>
</article>