<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<link type="text/css" href="<?php echo $this->baseUrl();?>/application/templates/front/css/style.css" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl();?>/application/templates/front/themes/2/js-image-slider.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl();?>/application/templates/front/themes/2/js-image-slider.js" type="text/javascript"></script>
 <?php echo $this->headScript();?>
<title>UNC</title>
	
	<!------------script-------------->
<div style="abc">
    <div id="divAdRight" style="DISPLAY: none; POSITION: absolute; TOP: 0px">
                	<a href="<?php echo $this->listquangcao4['ads_link']; ?>" target="_blank">
            		<?php
            		 	echo $this->listquangcao4['ads_banner']; 
            		?>
            		</a>
    </div>
</div>
    <div id="divAdLeft" style="DISPLAY: none; POSITION: absolute; TOP: 0px">
                    	<a href="<?php echo $this->listquangcao3['ads_link']; ?>" target="_blank">
            		<?php
            		 	echo $this->listquangcao3['ads_banner']; 
            		?>
            		</a>      
    </div>
    <script>
        function FloatTopDiv()
        {
            startLX = ((document.body.clientWidth -MainContentW)/2)-LeftBannerW-LeftAdjust , startLY = TopAdjust+80;
            startRX = ((document.body.clientWidth -MainContentW)/2)+MainContentW+RightAdjust , startRY = TopAdjust+80;
            var d = document;
            function ml(id)
            {
                var el=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
                el.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
                el.x = startRX;
                el.y = startRY;
                return el;
            }
            function m2(id)
            {
                var e2=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
                e2.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
                e2.x = startLX;
                e2.y = startLY;
                return e2;
            }
            window.stayTopLeft=function()
            {
                if (document.documentElement && document.documentElement.scrollTop)
                    var pY =  document.documentElement.scrollTop;
                else if (document.body)
                    var pY =  document.body.scrollTop;
                if (document.body.scrollTop > 30){startLY = 3;startRY = 3;} else {startLY = TopAdjust;startRY = TopAdjust;};
                ftlObj.y += (pY+startRY-ftlObj.y)/16;
                ftlObj.sP(ftlObj.x, ftlObj.y);
                ftlObj2.y += (pY+startLY-ftlObj2.y)/16;
                ftlObj2.sP(ftlObj2.x, ftlObj2.y);
                setTimeout("stayTopLeft()", 1);
            }
            ftlObj = ml("divAdRight");
            //stayTopLeft();
            ftlObj2 = m2("divAdLeft");
            stayTopLeft();
        }
        function ShowAdDiv()
        {
            var objAdDivRight = document.getElementById("divAdRight");
            var objAdDivLeft = document.getElementById("divAdLeft");       
            if (document.body.clientWidth < 1000)
            {
                objAdDivRight.style.display = "none";
                objAdDivLeft.style.display = "none";
            }
            else
            {
                objAdDivRight.style.display = "block";
                objAdDivLeft.style.display = "block";
                FloatTopDiv();
            }
        } 
    </script>
    <script>
    document.write("<script type='text/javascript' language='javascript'>MainContentW = 980;LeftBannerW = 125;RightBannerW = 125;LeftAdjust = -150;RightAdjust = 200;TopAdjust = 10;ShowAdDiv();window.onresize=ShowAdDiv;;<\/script>");
    </script>
		<!------------begin Script-------------->
</head>

<body>
<div>
	<!------------begin header-------------->
	<div id="header">
    	<div id="logo"> <h1 style="margin:0"><a href="<?php echo $this->baseUrl();?>"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.png"/></a></h1></div>
        <div id="right-header">
            <div id="right-header1"></div>

                        		<div class="right-header2">
                <div class="img-header"><a href="<?php echo $this->listquangcao1['ads_link']; ?>" target="_blank"><?php echo $this->listquangcao1['ads_banner']; ?></a></div>
            		<!--<p>12/8/2012 Khai giảng lớp liên thông vp2</p>-->
            			
            		</div>
            
        </div>
    </div>
    <!------------end header-------------->
    
    <!------------begin content-------------->
    <div id="content">
    	<!----------------begin-menu------------>
        <div id="top-menus">
        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_23.png" width="1000px" height="20px"/>
            <div id="top-menu">
            	<ul id="nav">
                	<li id="home"  class="top-fist" ><a class="top_link" href="<?php echo $this->baseUrl();?>"><div style="margin:7px 5px 0 6px; float:left"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/home.png"/></div> Trang chủ</a></li>
                	  <?php foreach($this->listParent as $parent)
					  {
					  ?>
                    <li class="top"><a class="top_link" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $parent['category_id']; ?>-1-<?php echo $parent['alias']; ?>.html"><span> <?php echo $parent['category_name'] ?><!--Lấy ra danh mục cha--></span></a>|
                    	<ul class="sub">     
                        		<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                            		<li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $child['category_id'];?>-1-<?php echo $child['alias'];?>.html"><?php echo $child['category_name']; ?></a></li>
                            	<?php
									}
								}
                            	?>                   	
                        </ul>
                    </li>
                    <?php }?>
                    <!-- li class="top"><a class="top_link" href="<?php echo $this->baseUrl(); ?>/video/list">Video</a>|</li-->
                    <li class="top"><a class="top_link" href="<?php echo $this->baseUrl(); ?>/video/danh-sach/1-trang.html">Video</a>|</li>
                    <li class="top"><a class="top_link" href="<?php echo $this->baseUrl(); ?>/forum">Forum</a></li>
                    
                </ul>
            </div>
        </div>
       	<!----------------end-menu------------>
        
        <!----------------begin-maincontent------------>
        <!----------------begin-slide------------>
    <div id="slides">
    <div id="item">Danh nhân văn hóa - Thiên cổ hùng văn - Giới thiệu các tác phẩm đương đại nổi tiếng - Văn đàn</div>
    <div id="slide">
	    <div id="left-slide">
	    <div id="sliderFrame">

        <div id="slider">
        	    	<?php 
                    foreach($this->listHotNewsJs as $news)
					{
				      	if($news['news_avatar'] != ""){
				    ?>
				      		 <a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']; ?>.html"><?php echo $news['news_avatar']; ?> </a>
				    <?php
				      	}
						else
							{
								?>
									<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-3.jpg" alt="Hello!!!" />
								<?php
							}
					}
                    ?>
            <!--<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-2.jpg" alt="Hello!!!" />
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-3.jpg" />
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-4.jpg" />
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-3.jpg" />-->
        </div>

        <!--thumbnails-->               	
        <div id="thumbs">
        	        <?php 
                    foreach($this->listHotNewsJs as $news)
					{
					?>
            <div class="thumb">
                <div class="thumb-content"><p><a style="line-height:15px" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']; ?>.html"><?php echo $news['news_title']; ?></a></p></div>
                <div style="clear:both;"></div>
            </div>
            		<?php
					}
                    ?>
           </div>

        <!--clear above float:left elements. It is required if above #slider is styled as float:left. -->
        <div style="clear:both;height:0;"></div>
    </div>
    </div>
<!-- End slider-->
<div id="right-slide">
                	<div id="rsl-1">
                    	<div id="rs1" class="rs">
                    		<p style="margin:0; text-align:center;line-height:25px" onclick="toggle_view('col1','col2');">Nóng nhất</p>
                    	</div>
                        <div id="rs2" class="rs" onclick="toggle_view('col2','col1');"><p style="margin:0; text-align:center;line-height:25px">Đọc nhiều nhất</p></div>
                    </div>
                    
                   <div id="col1">
                    <?php
                    $count = 0; 
                    foreach($this->listHotNews as $news)
					{
						$count++ ;
						?>
							<div class="risl-2">
								<?php if(isset($news['news_title']))
								{
								?>
								<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']; ?>.html">
								<?php 
									$charset = 'utf-8';
									$len = 35;
									$string = $news['news_title']; 
									$string = html_entity_decode($string, ENT_QUOTES, $charset);
									if(mb_strlen($string, $charset)> $len)
									{
										$arr = explode(' ', $string);
										$string = mb_substr($string, 0, $len, $charset);
										$arrRes = explode(' ', $string);
										$last = $arr[count($arrRes)-1];
									
										unset($arr);
										if(strcasecmp($arrRes[count($arrRes)-1], $last))
										{
											unset($arrRes[count($arrRes)-1]);
										}
										$string = implode(' ', $arrRes)."...";
									}
									echo $string;
								?>
								</a>
								<?php 
								}
								?>
							</div>
						<?php
						if($count == 6) break;
					}
                    ?>
                    </div>
                    
                    <div id="col2" style="display:none">
                    <?php 
                    foreach($this->listNewsMostView as $news)
					{
						?>
							<div class="risl-2"><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']?>.html">
								<?php 
									$charset = 'utf-8';
									$len = 40;
									$string = $news['news_title']; 
									$string = html_entity_decode($string, ENT_QUOTES, $charset);
									if(mb_strlen($string, $charset)> $len)
									{
										$arr = explode(' ', $string);
										$string = mb_substr($string, 0, $len, $charset);
										$arrRes = explode(' ', $string);
										$last = $arr[count($arrRes)-1];
									
										unset($arr);
										if(strcasecmp($arrRes[count($arrRes)-1], $last))
										{
											unset($arrRes[count($arrRes)-1]);
										}
										$string = implode(' ', $arrRes)."...";
									}
									echo $string;
								?></a></div>
						<?php
					}
                    ?>
                    </div>

        <!--clear above float:left elements. It is required if above #slider is styled as float:left. -->
        <div style="clear:both;height:0;"></div>
    </div>
    </div>
    	<?php
    		if(isset($_SESSION['home']))
			{
    	?>
            <div id="note-slide">
            	<div id="text-slide">
            		<p class="tieude">
                        	 <?php
                        		foreach($this->listHotNews as $childTintuc)

                        	    {
									{
                        		?>
                            		<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $childTintuc['news_id']; ?>-<?php echo $childTintuc['alias']; ?>.html"><?php echo $childTintuc['news_title']; ?></a>
                            		</p>
                        				<p><?php 
										$str = $childTintuc['news_summary']; 
										  $preg1 = preg_match_all('#<*>#',$str,$match);
										  
										  //var_dump($match);
										  if($preg1 > 1)
										  	$str = str_replace($match[0][0], "", $str);
										 	//$str = strip_tags($str);
												$charset = 'utf-8';
												$len = 300;
												$str = html_entity_decode($str, ENT_QUOTES, $charset);
												if(mb_strlen($str, $charset)> $len)
												{
													$arr = explode(' ', $str);
													$str = mb_substr($str, 0, $len, $charset);
													$arrRes = explode(' ', $str);
													$last = $arr[count($arrRes)-1];
												
													unset($arr);
													if(strcasecmp($arrRes[count($arrRes)-1], $last))
													{
														unset($arrRes[count($arrRes)-1]);
													}
													$str = implode(' ', $arrRes)."...";
												}
												
											
												
										  if($preg1 > 0)
										  {
				                    	 	$str = str_replace($match[0][0],"",$str);
										  }
										 echo $str;
										  
										 ?>                        					
                        				</p>

                            	<?php
                            			break;
									}
								}
                            	?>
                    <div>
                    	<div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg"/>
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg" />
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg"/>
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg" />
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                    </div>
                </div>
                <div id="rua-images">
                	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/RUA.png" />                    
                </div>
            </div>
            
        </div>
       </div>
        <!---------------end slide------------>
        <!---------------begin ads----------->
        <div id="ads">
        	<div id="left-ads">
            	<div id="tittle-adds">
                	<div id="logo-ads"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logoads.png"/></div>
                    <div id="tittles">
                    	<p id="p1">Lớp chia sẻ kinh nghiệm, kỹ năng thực tế:</p>
                        <p id="p2">Để làm việc tại Ngân Hàng</p>
                    </div>
                </div>
                <ul id="text-ads">
                	<li>Cung cấp các kỹ năng mềm, kỹ năng vượt qua cuộc phỏng vấn của nhà tuyển dụng và các bài tập tình huống: Phát triển năng lực và nguyện vọng của mỗi người đối với mỗi vị trí công việc cụ thể;</li>
                    <li> Nhận biết những rủi ro trong hoạt động nghề nghiệp, phương pháp vượt qua những rủi ro trong mọi lĩnh vực nhạy cảm như: hoạt động, tín dụng, hoạt động giao dịch, hoạt động thanh toán, ngân quỹ...</li>
                </ul>
            </div>
          	<div id="right-ads">
            	<a href="<?php echo $this->listquangcao2['ads_link']; ?>" target="_blank">
            		<?php
            		 	echo $this->listquangcao2['ads_banner']; 
            		?>
            		</a>
            </div>
        </div>
        
        <?php
        }
        ?>
        <!---------------end ads----------->
        
        <!---------------begin news---------->
        <div id="main-content">
        	<!------------begin tin tức------->
        	 <div id="news">
                
                <?php echo $this->layout()->content;?>
                
            </div>
            
            <!------------end tin tức------->
            <!------------begin video------->
            <div id="video">
            	<div id="tube">
                	<div id="vd">Video Clip</div>
                	<?php 
                		if(isset($this->video_default))
						{
	                		$video_default = $this->video_default;
							$video_default = trim($video_default);
							$video_default = str_replace("http://www.youtube.com/watch?v=","",$video_default);
							$video_default = substr($video_default,0,11);
						}
                	?>
                	<object width="300" height="230" style="margin-left:15px;">
                		<iframe width="300" height="230" src="http://www.youtube.com/embed/<?php if(isset($video_default)) echo $video_default; ?>" frameborder="0" allowfullscreen></iframe>
                	</object>

					
                </div>
                <?php
                       		foreach($this->listquangcao as $quangcao)
								{
									
                        		?>
                <div class="img-tube"><a href="<?php echo $quangcao['ads_link']; ?>" target="_blank">   <?php echo $quangcao['ads_banner']; ?></a></div>
                <?php   } ?>
            </div>
            <!------------end video------->
        </div>
       
        <!---------------end news----------->
        
        <!----------------end-maincontent------------>
    </div>
    <!------------end content-------------->
    
    <!------------begin footer-------------->
    <div id="footer">
    	<div id="search-footer">
        	<form class="form" action="<?php echo $this->baseUrl();?>/timkiem" name="search-form" method="post">
            	<input type="text" value="" name="search-text" style="background:url(<?php echo $this->baseUrl();?>/application/templates/front/images/search.png) no-repeat; background-color:#FFF; padding-left:20px" />
            	<input type="submit" name="submit" value="Tìm kiếm" />
            </form>
        </div>
        <div id="menu-footer">
        	<ul>
            		<li><a href="<?php echo $this->baseUrl();?>"> Trang chủ</a></li><li>|</li>
					<?php foreach($this->listParent as $parent)
					  {
					  ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $parent['category_id']; ?>-1-<?php echo $parent['alias']; ?>.html"><span> <?php echo $parent['category_name'] ?><!--Lấy ra danh mục cha--></span></li></a><li>|</li>
					<?php } ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/video/danh-sach/1-trang.html">Video</a></li><li>|</li>
                    <li><a href="#">Forum</a></li></li>
            </ul>
        </div>
        <div id="copyright">Địa chỉ: Tòa nhà CT5B - Mễ Trì Thượng - Từ Liêm - Hà Nội. Điện thoại: (+84) 85898964. Email: support@niw.com.vn<br/><br/>© Copyright NIW – Công ty TNHH Công nghệ phần mềm - Design by <a href="http://niw.com.vn/">NIW</a></div>
    </div>
    <!------------end footer-------------->
</div>
</body>
</html>
