<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
				function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa video này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/video/del/videoid/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header>
		<h3><?php echo $this->title;?></h3>
		<!--a class="alt_btn" style="float:right;margin-top: -3%;margin-right: 3px;" href="<?php echo $this->baseUrl('admin/uploadvideo/refresh');?>">Làm mới</a-->
	</header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
	$(document).ready(function() {
		$('#listnews').dataTable({
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25
		});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Thứ tự</th>
				<th>Tiêu đề</th>
				<th>Mô tả</th>
				<th>Thành viên</th>
				<th>Kích hoạt</th>
				<th>Sửa</th>
				<th>Xóa</th>
			</thead>
			<tbody>
				<?php 
				$count=1;
				foreach ($this->list as $item)
				{?>
					<tr>
						<td><?php echo $count;?></td>
						<td><?php echo $item['video_title'];?></td>
						<td><?php echo $item['video_description'];?></td>
						<td><?php echo $item['user_upload'];?></td>
						<td><?php if($item['is_active'] == '1') echo 'Có'; else echo 'Không';?></td>
						<td><a href="<?php echo $this->baseUrl();?>/admin/video/edit/videoid/<?php echo $item['video_id']?>" title="Sửa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a></td>
						<td><a class="del_button" onclick="confirmDel(<?php echo $item['video_id']?>)" title="Xóa"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a></td>
					</tr>
				<?php $count++; }?>
			</tbody>
		</table>
		
		<footer>
			<div class="submit_link" style="float:right">
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/video/upload');?>">Upload</a>
			</div>
			<div class="submit_link" style="float:left; font-weight: bold;">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>
