<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/jquery.ui.all.css">
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.datepicker.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/demos.css">
<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
<script type="text/javascript">
	$(function() {
		$( ".datepicker" ).datepicker();
	});
	$(document).ready(function(){
		$("#thongke-form").submit(function(){
			var from=$("#fromdate").val().replace('/','-').replace('/','-');
			var to=$("#todate").val().replace('/','-').replace('/','-');
			if (from=='' || to=='')
			{
				alert("Hãy chọn ngày bắt đầu và ngày kết thúc");
				return false;
			}
			var name=$(this).val();
			if (name!='')
				$("#datatable").load("<?php echo $this->baseUrl();?>/admin/tinhtien/thongke/name/"+name+"/fromdate/"+from+"/todate/"+to);
			else
				$("#datatable").load("<?php echo $this->baseUrl();?>/admin/tinhtien/thongke/fromdate/"+from+"/todate/"+to);
			return false;
		});
		$("#name-selector").keypress(function(e){
			var code = (e.keyCode ? e.keyCode : e.which);
			if (code==13)
			{
				$("#listnews").html("");
				var name=$(this).val();
				for (var i=0; i<name.length; i++)
				{
					if (name[i]==" ")	
					name=name.replace(" ","***");
				}
				var from=$("#fromdate").val().replace('/','-').replace('/','-');
				var to=$("#todate").val().replace('/','-').replace('/','-');
				if (from!='')
				{
					if (to=='') to='<?php echo date('Y-m-d',time()+7*3600);?>';
					$("#datatable").load("<?php echo $this->baseUrl();?>/admin/tinhtien/thongke/name/"+name+"/fromdate/"+from+"/todate/"+to);
				}
			}
		});
		if ($("#fromdate").val()!='' && $("#todate").val()!='')
			$("#thongke-form").submit();
	});
</script>
<fieldset style="margin:15px; padding:15px; width:20%; float:right">
	<form action="<?php echo $this->baseUrl()?>/admin/tinhtien/price" method="post" name="price-form" id="price-form">
		<h2>Giá tiền nhuận bút</h2>
		<p>Viết bài mới: <input style="width:auto !important" type="text" name="new-post-price" id="new-post-price" value="<?php echo $this->price_post['price'];?>"/></p>
		<br/>
		<p>Duyệt tin tự động: <input style="width:auto !important" type="text" name="review-price" id="review-price" value="<?php echo $this->price_review['price'];?>"/></p>
		<br/>
		<br/>
		<?php if ($_SESSION['role_id']=='0')
		{?>
			<input type="submit" value="Cập nhật"/>
		<?php }?>
	</form>
</fieldset>
<div style="float:left; padding:0 15px">
	<h2>Tính tiền hoa hồng cho bài báo</h2>
	<?php
	?>

	<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/tinhtien/thongke" name="thongke-form" id="thongke-form">
		<p>Từ ngày <span style="color:red;">(*)</span>: <input style="padding-left: 10px;" type="text" name="fromdate" id="fromdate" class="datepicker" value="<?php if (isset($_SESSION['from_date'])) echo $_SESSION['from_date']?>"/>
		Tới ngày <span style="color:red;">(*)</span>: <input style=" padding-left: 10px;" type="text" name="todate" id="todate" class="datepicker" value="<?php if (isset($_SESSION['to_date'])) echo $_SESSION['to_date']?>"/>
		<input name="Search" value="Search" type="submit"/>
		</p>
	</form>
	<label>Chọn theo tên: 
		<input type="text" name="name-selector" id="name-selector"/>
		<i>(Điền và gõ Enter để tìm kiếm)</i>
	</label>
	<div id="datatable">
	</div>
	<div class="yui3-skin-sam">
				<div class="example yui3-skin-sam" id="listnews">
				</div>
			</div>
</div>		