<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
			<script type="text/javascript">
				YUI().use("datatable-sort",'datatable','gallery-paginator-view', 'gallery-datatable-paginator', function (Y) {
					var data = [
												<?php 
														$count=0;
														foreach ($this->listUser as $item)
														{?>
															{ stt: '<?php echo $count+1;?>', 
																username: '<?php echo $this->listUser[$count]['user_login'];?>',
																ho_ten: '<?php echo $this->listUser[$count]['user_fullname'];?>',
																chuc_vu: '<?php if ($this->listUser[$count]['role_id']==1) echo 'Trưởng ban'; else echo 'Phóng viên';?>',
																so_tien: '<?php echo $this->listMoney[$count];?>',
																post: '<?php echo $this->listPost[$count];?>',
																check: '<?php echo $this->listCheck[$count];?>'
															},
														<?php $count++;}?>
													];
					var pagModel = new Y.PaginatorModel({itemsPerPage:10});
					var cols=[{
									key: 'stt',
									label: 'STT',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true // Must be set or the html will be escaped
								},
								{
									key: 'username',
									label: 'Username',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								},
								{
									key: 'ho_ten',
									label: 'Họ tên',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								},
								{
									key: 'chuc_vu',
									label: 'Chức vụ',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								},
								{
									key: 'so_tien',
									label: 'Số tiền',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								},
								{
									key: 'post',
									label: 'Bài viết mới',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								},
								{
									key: 'check',
									label: 'Bài duyệt',
									sortable:true,
									formatter: '<span>{value}</span>',
									allowHTML: true 
								}];
					var table = new Y.DataTable({
						columns: cols,
						data: data,
						width: 300,
						paginator: new Y.PaginatorView({
				            model:          pagModel,
				            sortable: true,
				            dynamicData:true,
				            sortedBy : {key:"news_title"},
				            container:      '#pagContainerBar',
				            paginatorTemplate:  '<a href="#" data-pglink="first" class="{pageLinkClass}" title="First Page">First</a> | '+
	                        '<a href="#" data-pglink="prev" class="{pageLinkClass}" title="Prior Page">Prev</a> | '+
	                        '{pageLinks} | <a href="#" data-pglink="next" class="{pageLinkClass}" title="Next Page">Next</a> | '+
	                        '<a href="#" data-pglink="last" class="{pageLinkClass}" title="Last Page">Last</a> &nbsp; Rows/Page: {selectRowsPerPage}'}),
				        resizePaginator: true
					});
		
					table.render("#listnews");
				});
			</script>
	<div class="yui3-skin-sam">
				<div class="example yui3-skin-sam" id="listnews">
				</div>
			</div>
