<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('#listnews').dataTable({
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25
		});
	});
</script>
<style type="text/css">
.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
</style>
<div class="tab_container" style="width:735px">
	<table id="listnews">
		<thead>
			<th>Thứ tự</th>
			<th>Tên đăng nhập</th>
			<th>Họ tên</th>
			<th>Chức vụ</th>
			<th>Số tiền</th>
			<th>Bài viết mới</th>
			<th>Bài duyệt</th>
		</thead>
		<tbody>
			<?php 
			$count=0;
			foreach ($this->listUser as $item)
			{?>
				<tr>
					<td><?php echo $count+1;?></td>
					<td><?php echo $this->listUser[$count]['user_login'];?></td>
					<td><?php echo $this->listUser[$count]['user_fullname'];?></td>
					<td><?php if ($this->listUser[$count]['role_id']==1) echo 'Trưởng ban'; else echo 'Phóng viên';?></td>
					<td><?php echo $this->listMoney[$count];?></td>
					<td><?php echo $this->listPost[$count];?></td>
					<td><?php echo $this->listCheck[$count];?></td>
				</tr>
			<?php $count++;}?>
		</tbody>
	</table>

</div>