  <?php foreach($this->listParent as $parent)
  {
  ?>
  <div class="item-news">
                    <div class="van">
                    	<div class="tittle-van"><p><?php echo $parent['category_name'] ?></p></div>                   
                        <div class="border">
                        	<ul>
                        		<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                            		<li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $child['category_id']; ?>-<?php echo $child['alias']; ?>.html"><?php echo $child['category_name']; ?></a></li><li>|</li>
                            	<?php
									}
								}
                            	?>
                            </ul>
                        </div>
                    </div>
                    <div class="item-new-left">
                    	 <?php
                        		foreach($this->listNews[$parent['category_id']] as $childTintuc)

                        	    {
                        	    	//var_dump($childTintuc);die();
                         ?>
			                    	<!--<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_63.png"/>-->
										
			                    	<?php $str = $childTintuc['news_avatar']; 
			                    		  $preg = preg_match_all('#<img.*/>#',$str,$match);
										  if($preg > 0)
										  {
				                    	 	//$str = str_replace($match[0][0],"",$str);
											echo $match[0][0];
										  }
										  else{ 
										  	?>
			                    		<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.png"/>
			                    		

                          			<?php
									}
                            	break;
								}
                          ?>                    	
                        <p class="tittle">
                        	 <?php
                        		foreach($this->listNews[$parent['category_id']] as $childTintuc)

                        	    {
									{
                        		?>
                            		<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $childTintuc['news_id']; ?>-<?php echo $childTintuc['alias']; ?>.html"><?php echo $childTintuc['news_title']; ?></a>
                            		</p>
                        				<p><?php 
										$str = $childTintuc['news_summary']; 
										  $preg1 = preg_match_all('#<.*>#',$str,$match);
										  
										  //var_dump($match);
										  if($preg1 > 1)
										  	$str = str_replace($match, "", $str);
										 
												$charset = 'utf-8';
												$len = 260;
												$str = html_entity_decode($str, ENT_QUOTES, $charset);
												if(mb_strlen($str, $charset)> $len)
												{
													$arr = explode(' ', $str);
													$str = mb_substr($str, 0, $len, $charset);
													$arrRes = explode(' ', $str);
													$last = $arr[count($arrRes)-1];
												
													unset($arr);
													if(strcasecmp($arrRes[count($arrRes)-1], $last))
													{
														unset($arrRes[count($arrRes)-1]);
													}
													$str = implode(' ', $arrRes)."...";
												}
												
											
												
										  if($preg1 > 0)
										  {
				                    	 	$str = str_replace($match[0][0],"",$str);
										  }
										 echo $str;
										  
										 ?>                        					
                        				</p>

                            	<?php
                            			break;
									}
								}
                            	?>
                        
                    </div>
                    <div class="item-new-right">
                    	<ul>
                        	
                        		<?php
                        		foreach($this->listNews[$parent['category_id']] as $tintuc)
								{
									{
											?>
											<li><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/sao.png"/>
											<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $tintuc['news_id']; ?>-<?php echo $tintuc['alias']; ?>.html">
												<?php 
												$str = $tintuc['news_title'];
												$charset = 'utf-8';
												$len = 40;
												$str = html_entity_decode($str, ENT_QUOTES, $charset);
												if(mb_strlen($str, $charset)> $len)
												{
													$arr = explode(' ', $str);
													$str = mb_substr($str, 0, $len, $charset);
													$arrRes = explode(' ', $str);
													$last = $arr[count($arrRes)-1];
												
													unset($arr);
													if(strcasecmp($arrRes[count($arrRes)-1], $last))
													{
														unset($arrRes[count($arrRes)-1]);
													}
													$str = implode(' ', $arrRes)."...";
												}
												echo $str;
												?>
											</a>
											</li>
											<?php
									}
								}
                            	?>
                        	
                         
                        </ul>
      				</div>
      				
</div>
<?php
}
?>