<?php function cutString($str,$limit)
{
	if (strlen($str)>$limit)
	{
		while ($str[$limit]!=' ')
			$limit++;
	}
	else $limit=strlen($str);
	return substr($str, 0, $limit);
}?>

<?php foreach($this->listParent as $parent)
  {
  ?>
	<div class="news">
             <!--------begin bản tin-------->
                <div class="item-news">
                	<div class="children_down-title" style="margin-top:0px"><a><?php echo $parent['category_name'] ?></a></div>
                	<div class="subpage_wapper_left_top">
                		<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                        			<div class="children_down2">
                        				<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $child['category_id']; ?>-<?php echo $child['alias']; ?>.html"><?php echo $child['category_name']; ?></a>
                        			</div>
                        			<div class="children_down">|</div>
                        		<?php
									}
								}
                            	?>
           			</div>
                    <div class="item-new-left">
                    	<?php $list=$this->listNews[$parent['category_id']];
                    	$childTintuc=$list[0];
                    	$str = $childTintuc['news_avatar']; 
                    		  $preg = preg_match_all('#<img.*/>#',$str,$match);
							  if($preg > 0)
							  {
	                    	 	//$str = str_replace($match[0][0],"",$str);
								echo $match[0][0];
							  }
							  else{ ?>
							  	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.gif"/>
							  <?php }?>
                        <p class="tittle"><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $childTintuc['news_id']; ?>-<?php echo $childTintuc['alias']; ?>.html"><?php echo $childTintuc['news_title']; ?></a></p>
                        <p><?php $summary=strip_tags($childTintuc['news_summary']);
                        	echo str_replace(array("\n","\r"),"",cutString($summary, 500));?></p>
                    </div>
                    <div class="item-new-right">
                    	<ul>
                    		<?php
                    			$count=0;
                        		foreach($this->listNews[$parent['category_id']] as $tintuc)
								{
									if ($count<5){
											?>
										<li><img class="img4" src="<?php echo $this->baseUrl();?>/application/templates/front/images/cham_tintuc.gif"/>
											<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $tintuc['news_id']; ?>-<?php echo $tintuc['alias']; ?>.html"><?php echo $tintuc['news_title'];?></a>
										</li>
									<?php $count++;}
							}?>
                        </ul>
                        <div class="clear"> </div>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="clear"> </div>
               <!---------end bản tin------->
               </div>  
<?php }?>