<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()?>
	<?php echo $this->headScript()?>
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
    
	<script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-35457656-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/paginator/assets/skins/sam/paginator.css" />
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/datatable/assets/skins/sam/datatable.css" />
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/button/assets/skins/sam/button.css" />
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/yuiloader/yuiloader-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/event/event-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/connection/connection-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/json/json-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/dom/dom-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/element/element-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/paginator/paginator-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/datasource/datasource-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/event-delegate/event-delegate-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/datatable/datatable-min.js"></script>
	<script type="text/javascript" src="http://yui.yahooapis.com/2.9.0/build/button/button-min.js"></script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			$(".submenu").slideUp();
			$(".icn_application").css("cursor","pointer");
			$(".icn_application").click(function(){
				$(this).children(".submenu").slideToggle();
			});
		});
	</script>
</head>


<body>
	<header id="header">
	<hgroup>
		<h1 class="site_title"><a href="<?php echo $this->baseUrl();?>/admin">Trang quản trị</a></h1>
		<h2 class="section_title">Bảng điều khiển</h2><div class="btn_view_site"><a href="<?php echo $this->baseUrl();?>">Hiển thị web</a></div>
	</hgroup>
</header> <!-- end of header bar -->
<section id="secondary_bar">
	<div class="user">
	<p>Quản trị viên</p>
</div>	<div class="breadcrumbs_container">
	<article class="breadcrumbs">
		<a href="<?php echo $this->baseUrl();?>/admin">Trang quản trị</a>
		<div class="breadcrumb_divider"></div> <a class="current">Bảng điều khiển</a>
	</article>
	<article style="float:right;margin-right:49px" class="breadcrumbs">
		<?php
		if($_SESSION['role'] == "0")
		{
			?>
				<a href="<?php echo $this->baseUrl();?>/admin/edit/index/userid/<?php echo $_SESSION['user_id']; ?>">Hồ sơ</a>
			<?php
		}
		else if($_SESSION['role'] == "1")
		{
			?>
				<a href="<?php echo $this->baseUrl();?>/admin/truongban/edit/userid/<?php echo $_SESSION['user_id']; ?>">Hồ sơ</a>
			<?php		
		}
		else if($_SESSION['role'] == "2")
		{
			?>
				<a href="<?php echo $this->baseUrl();?>/admin/phongvien/edit/userid/<?php echo $_SESSION['user_id']; ?>">Hồ sơ</a>
			<?php		
		}
		?>
	</article>
	</div></section><!-- end of secondary bar -->	
	<aside id="sidebar" class="column">
				<hr/>
<h3>Mục quản lý</h3>
	<ul class="toggle">
		<li class="icn_application"><a>Quản lý chung</a>
			<ul class="submenu">
				<li><a href="<?php echo $this->baseUrl();?>/admin/phongvien">Phóng viên</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/truongban">Trưởng ban</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/tinhtien">Nhuận bút</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/thamdo">Thăm dò ý kiến</a></li>
			</ul>
		</li>
		<li class="icn_application"><a>Quản lý tin tức</a>
			<ul class="submenu">
				<li><a href="<?php echo $this->baseUrl();?>/admin/tintuc/index/viewtype/1">Tin tức</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/chuyenmuc">Chuyên mục tin tức</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/getnewssetting">Cài đặt lấy tin tự động</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/comment">Bình luận</a></li>
			</ul>
		</li>
		<li class="icn_application"><a>Quản lý video</a>
			<ul class="submenu">
				<li><a href="<?php echo $this->baseUrl();?>/admin/videocategory">Chuyên mục Video</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/uploadvideo">Tải video lên Youtube</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/video">Tải video lên UNC</a></li>
			</ul>
		</li>
		<li class="icn_application"><a>Quản lý ảnh</a>
			<ul class="submenu">
				<li><a href="<?php echo $this->baseUrl();?>/admin/imagecategory">Chuyên mục ảnh</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/quangcao">Quảng cáo</a></li>
				<li><a href="<?php echo $this->baseUrl();?>/admin/image">Hình ảnh</a></li>
			</ul>
		</li>
		<li class="icn_application"><a href="<?php echo $this->baseUrl();?>/admin/diachi">Địa chỉ liên kết</a></li>
	</ul>
<h3>Hệ thống</h3>
	<ul class="toggle">
		<li class="icn_jump_back"><a href="<?php echo $this->baseUrl();?>/admin/index/logout">Đăng xuất</a></li>
	</ul>
		<footer>
	<hr />
</footer>	</aside><!-- end of sidebar -->

	<section id="main" class="column">
        <!-- article class="module width_full">
		<header><h3>Stats</h3></header>
			<div class="module_content">
				<article class="stats_graph">
					<img src="http://chart.apis.google.com/chart?chxr=0,0,3000&chxt=y&chs=520x140&cht=lc&chco=76A4FB,80C65A&chd=s:Tdjpsvyvttmiihgmnrst,OTbdcfhhggcTUTTUadfk&chls=2|2&chma=40,20,20,30" width="520" height="140" alt="" />
				</article>
				
				<article class="stats_overview">
					<div class="overview_today">
						<p class="overview_day">Today</p>
						<p class="overview_count">1,876</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,103</p>
						<p class="overview_type">Views</p>
					</div>
					<div class="overview_previous">
						<p class="overview_day">Yesterday</p>
						<p class="overview_count">1,646</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,054</p>
						<p class="overview_type">Views</p>
					</div>
				</article>
				<div class="clear"></div>
			</div>
		</article><div class="spacer"></div -->
		<?php echo $this->layout()->content;?>
	</section>
</body>

</html>