<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/danhmuc/add">
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>ID</th> 
	    				<th>Tên danh mục</th> 
	    				<th>Danh mục cha</th>
	    				<th>Kích hoạt</th>
	    				<th>Actions</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{?>
				 		<tr>  
		    				<td><?php echo $item['category_id'];?></td> 
		    				<td><?php echo $item['category_name'];?></td>
		    				<td><?php echo $item['category_parent_id'];?></td>
		    				<td><?php echo $item['is_active'];?></td> 
		    				<td>
		    					<a href="<?php echo $this->baseUrl(); ?>/admin/danhmuc/edit?id=<?php echo $item['category_id']; ?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    				<a href="<?php echo $this->baseUrl(); ?>/admin/danhmuc/del?id=<?php echo $item['category_id']; ?>" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    				</td>
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
			<form>
				<div class="submit_link">
					<input type="submit" name="submit" value="Add new" class="alt_btn">
				</div>
			</form>
		</footer>
	</div>
	</form>
</article>