<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>ID</th> 
	    				<th>Tên danh mục</th> 
	    				<th>Danh mục cha</th>
	    				<th>Kích hoạt</th>
	    				<th>Actions</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{?>
				 		<tr>  
		    				<td><?php echo $item['category_id'];?></td> 
		    				<td><?php echo $item['category_name'];?></td>
		    				<td><?php echo $item['category_parent_id'];?></td>
		    				<td><?php if ($item['is_active']=='1') echo 'Bật'; else echo 'Tắt';?></td>
		    				<td>
		    					<a href="<?php echo $this->baseUrl(); ?>/admin/danhmuc/edit/category_id/<?php echo $item['category_id']; ?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    				<a href="<?php echo $this->baseUrl(); ?>/admin/danhmuc/del/category_id/<?php echo $item['category_id']; ?>" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    				</td>
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
			<form>
				<div class="submit_link">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/danhmuc/insert');?>">Thêm mới</a>
				</div>
		</footer>
	</div>
	</form>
</article>