<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tên danh mục : </label>
					<?php echo $this->form->getElement('category_name');?>
				</fieldset>
				
				<fieldset>
					<label>Danh mục cha : </label>
					<select name="category_parent_id">
					<option value="0"></option>
					<?php
						foreach($this->list as $item)
						{
							?>
								<option value="<?php echo $item['category_id']; ?>"><?php echo $item['category_name']; ?></option>	
							<?php 
						}
					?>
				</select>
				</fieldset>
				<fieldset>
					<label>Kích hoạt : </label>
					<?php echo $this->form->getElement('is_active');?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Thêm mới" class="alt_btn">
			</div>
		</footer>
	</article>
</form>