<script style="text/javascript">
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=116608581828346";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="detail">
	<div style="margin:10px" id="video_title">
		<h2 style="color:blue"><?php echo $this->video['video_title']; ?></h2>
	</div>
	<div id="video" style="float:left;margin:0px 10px 10px 10px">
		<iframe width="640" height="360" src="http://www.youtube.com/embed/5QlxJezCDOY" frameborder="0" allowfullscreen></iframe>
	</div>
	<div style="margin-top:400px;margin-left:10px" id="video_description">
		<h3>Mô tả : <i><?php echo $this->video['video_description']; ?></i></h3>
	</div>
	<div id="fb-root"></div>
	<div class="fb-like" data-href="http://www.niwvietnam.info/unc/" data-send="true" data-width="450" data-show-faces="true"></div>
	<hr/>
	<?php
	if(isset($_SESSION['logged']))
	{
		?>
			<h3>Bạn đang đăng nhập bằng tài khoản <span style="color:red"><?php echo $_SESSION['logged']; ?></span>&nbsp;&nbsp;&nbsp;
			<a style="text-decoration: none" href="<?php echo $this->baseUrl(); ?>/tintuc/logout"><i>Thoát</i></a></h3>
			<form method="post" action="<?php echo $this->baseUrl();?>/video/addcomment/videoid/<?php echo $this->video['video_id']; ?>/readerid/<?php echo $_SESSION['reader_id']; ?>">
				<div id="addComment">
					<textarea style="width:100%" rows="5"></textarea>
					<input type="submit" name="submit" value="Gửi bình luận"/>
				</div>
			</form>
				
		<?php
	}
	else 
	{
		?>
			<form method="post" action="<?php echo $this->baseUrl(); ?>/video/login/videoid/<?php echo $this->video['video_id']; ?>">
				<div id="login">
					<h3>Đăng nhập bằng tài khoản forum UNC để bình luận về video này</h3>
					<hr/>
					<span>Tên đăng nhập : </span><?php echo $this->form->getElement('user_name'); ?><br/>
					<span>Mật khẩu : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
						<?php echo $this->form->getElement('pass_word'); ?><br/>
					<input style="margin-left:20%" type="submit" name="submit" value="Đăng nhập"/>
				</div>
				<?php
				if(isset($_SESSION['fail'])) 
				{
					?>
						<h3><i style="color:red"><?php echo $_SESSION['fail'];unset($_SESSION['fail']);?></i></h3>
					<?php
				}
				?>
			</form>
		<?php
	}
	?>	
	
	<div id="comment">
		<hr/>
		<h3>Danh sách bình luận</h3>
		<hr/>
		<?php
		$count = 0;
		if($this->listComment > 0)
		{
			foreach($this->listComment as $comment)
			{
			?>
				<div>
					<h3 style="margin-left:40px"><i><?php echo $this->listUser[$count]['username']; ?></i></h3>
					<p style="margin-left:50px"><?php echo $comment['comment_content']; ?></p>
				</div>
				<hr/>
			<?php
			}
		}
		?>
	</div>
	
</div>