<script style="text/javascript">
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=116608581828346";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<?php
if(isset($this->video['video_full_link']))
{
	$video = $this->video['video_full_link'];
	$video = trim($video);
	$video = str_replace("http://www.youtube.com/watch?v=","", $video);
	$video = substr($video,0,11);
}
?>
<div id="detail">
	<div style="margin:10px" id="video_title">
		<h2 style="color:blue"><?php echo $this->video['video_title']; ?></h2>
	</div>
	<div id="video" style="float:left;margin:0px 10px 10px 10px">
		<iframe width="640" height="360" src="http://www.youtube.com/embed/<?php if(isset($video)) echo $video; ?>" frameborder="0" allowfullscreen></iframe>
	</div>
	<div style="margin-top:400px;margin-left:10px" id="video_description">
		<h3>Mô tả : <i><?php echo $this->video['video_description']; ?></i></h3>
	</div>
	<div id="fb-root"></div>
	<div class="fb-like" data-href="http://www.niwvietnam.info/unc/" data-send="true" data-width="450" data-show-faces="true"></div>
	<hr/>
	<?php
	if(isset($_SESSION['logged']))
	{
		?>
			<h3>Bạn đang đăng nhập bằng tài khoản <span style="color:red"><?php echo $_SESSION['logged']; ?></span>&nbsp;&nbsp;&nbsp;
			<a style="text-decoration: none" href="<?php echo $this->baseUrl(); ?>/tintuc/logout"><i>Thoát</i></a></h3>
			<form method="post" action="<?php echo $this->baseUrl();?>/video/addcomment/videoid/<?php echo $this->video['video_id']; ?>/readerid/<?php echo $_SESSION['reader_id']; ?>">
				<div id="addComment">
					<textarea name="comment_content" style="width:100%" rows="5"></textarea>
					<input type="submit" name="submit" value="Gửi bình luận"/>
				</div>
			</form>
				
		<?php
	}
	else 
	{
		?>
			<form method="post" action="<?php echo $this->baseUrl(); ?>/video/login/videoid/<?php echo $this->video['video_id']; ?>">
				<div id="login">
					<h3>Đăng nhập bằng tài khoản forum UNC để bình luận về video này</h3>
					<hr/>
					<table>
						<tr>
							<td>Tên đăng nhập : </td>
							<td><?php echo $this->form->getElement('user_name'); ?></td>
						</tr>
						<tr>
							<td>Mật khẩu : </td>
							<td><?php echo $this->form->getElement('pass_word'); ?></td>
						</tr>
					</table>
					<input style="margin-left:20%" type="submit" name="submit" value="Đăng nhập"/>
				</div>
				<?php
				if(isset($_SESSION['fail'])) 
				{
					?>
						<h3><i style="color:red"><?php echo $_SESSION['fail'];unset($_SESSION['fail']);?></i></h3>
					<?php
				}
				?>
			</form>
		<?php
	}
	?>	
	
	<div id="comment">
		<hr/>
		<h3>Danh sách bình luận</h3>
		<hr/>
		<?php 
		$count = 0;
		if(count($this->listComment) > 0)
		{
			foreach($this->listComment as $comment)
			{
				if($this->listImage[$count] == 0)
				{
				?>
					<img alt="" src="http://1.gravatar.com/avatar/b0eb17f97a5c244abfd54d0192e00a4d?s=68&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D68&amp;r=G" class="avatar avatar-68 photo" height="68" width="68">
				<?php 
				}
				else
				{
					?>
						<img alt="" src="<?php echo $this->baseUrl(); ?>/forum/image.php?u=1&dateline=<?php echo $this->listImage[$count]; ?>" class="avatar avatar-68 photo" height="68" width="68">
					<?php
				}
				
				?>
				<div style="#373737;background-color:#E4E4E4;margin-left:80px;margin-top:-67px;border-radius: 5px;border: 1px solid #ddd;padding: 10px;width:85%">
					<div style="margin-left:10px">
						<span style="color:blue;"><?php echo $this->listUser[$count]['username'] ?></span>   :   <span><?php echo $comment['comment_time']; ?></span> đã bình luận :
					</div>
					<div style="margin:20px">
						<?php echo $comment['comment_content']; ?>
					</div>
				</div>
				<br style="clear:both">
			<?php 
				$count++;
			}
		}
		else 
		{
			echo 'Video này chưa có bình luận nào';
		}
		?>
	</div>
	
</div>