<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/jquery.media.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/jquery.metadata.v2.js" type="text/javascript"></script>
<script type="text/javascript"">
	$(document).ready(function () {
		$('.media').media();
	});
</script>
<a href="<?php echo $this->baseUrl()?>/mediaplayer.swf?file=video/123.flv" class="media {width:250, height:250 ,caption: false, attrs: { attr1: 'attrValue1' }}">FLV File</a>
