<style type="text/css">
	.video{margin-top:10px}
</style>
<div class="video">
	<?php 
		foreach($this->list as $video)
		{
	?>
		<div class="video">
			<a style="color:blue;" href="<?php echo $this->baseUrl(); ?>/video/detail/videoid/<?php echo $video['video_id']; ?>" title="<?php echo $video['video_title']; ?>">
				<img class="img130" src="http://img.youtube.com/vi/<?php echo $video['video_link']; ?>/1.jpg"/>
			</a>
	 		<div>
	  			<a href="<?php echo $this->baseUrl(); ?>/video/detail/videoid/<?php echo $video['video_id']; ?>"><h3 style="color:blue;margin-left:145px;margin-top:-92px"><?php echo $video['video_title']; ?></h3></a>
	  			<div style="margin-left:145px">
					<?php echo $video['video_description']; ?>
	  			</div>
	 		</div>
	 		<br/><br/><br/>
	 		<br style="clear:both">
	 	</div>
	 	
 	<?php
		}
 	?>
</div>
<div style="margin:10px 0 10px 42%;">
<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
</div>