<div class="subpage_wapper_right">
              <div id="news" class="bgnews2" style="margin-top:0">
            	<div class="news_title2">
                	Ảnh đẹp
                </div>
                <ul>
                	<?php
                	if(count($this->listImageRight) > 0)
					{
						foreach($this->listImageRight as $imageRight)
						{
							$preg = preg_match_all('#<img.*/>#',$imageRight['image_link'],$match);
							?>
								<li class="even">
									<?php echo $match[0][0]; ?>
								</li>
							<?php
						}
					}
                	?>
                </ul>
                <p class="read_add"><a href="<?php echo $this->baseUrl() ?>/hinhanh/list/category_id/0">Xem thêm</a></p>
                <br style="clear:both">
            </div>
        </div>