<div class="subpage_wapper_right">
              <div id="news" class="bgnews2">
            	<div class="news_title2">
                	Ảnh đẹp
                </div>
                <ul>
                	<?php
                	if(count($this->listImageRight) > 0)
					{
						foreach($this->listImageRight as $imageRight)
						{
							$preg = preg_match_all('#<img.*/>#',$imageRight['image_link'],$match);
							?>
								<li class="even"><a href="#"><?php echo $match[0][0]; ?></a></li>
							<?php
						}
					}
                	?>

                </ul>
                <p class="read_add"><a href="#">Xem thêm</a></p>
                <br style="clear:both">
            </div>
        </div>