<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>UNC subpage</title>
<link href="<?php echo $this->baseUrl();?>/application/templates/front/css/style.css" type="text/css" rel="stylesheet" />
<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/switch_news.js" type="text/javascript"></script>
</head>

<body>
	 <!-----------begin header-------------->
	<div id="header">
    	<div id="center-header">
        	<div id="subpage_logo"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.gif"/></div>
            <div id="subpage_search">
            	<form class="searchform" action="" method="post">
				<input name="search-text" class="t" onfocus="if (this.value == 'Tìm kiếm …') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Tìm kiếm …';}" type="text" value="Tìm kiếm …">
				<input class="searchsubmit" type="submit" value="" style="cursor:pointer">
			</form>
            </div>  
            			<!--------Menu-Top------>
			<div id="menu-top">
				<ul id="nav">
					<?php foreach($this->listParent as $parent)
					  {
					  ?>
					  	<li class="item ">
				            <a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $parent['category_id']; ?>-1-<?php echo $parent['alias']; ?>.html"><?php echo $parent['category_name'] ?></a>
				            <ul class="sub">
				            	<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                        			<li class="itemSub">
					                    <a class="a-style" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $child['category_id'];?>-1-<?php echo $child['alias'];?>.html"><?php echo $child['category_name']; ?></a>|
					                </li>
                        		<?php }
									}?>
				            </ul>
				        </li>
					  <?php }?>
			        <li class="item">
			            <a href="<?php echo $this->baseUrl(); ?>/video/danh-sach/1-trang.html">Video</a>
			        </li>
			        <li class="item">
			            <a href="<?php echo $this->baseUrl(); ?>/forum">Forum</a>
			        </li>
			    </ul>
       </div>
        <!-----------end menu---------------> 	          
        </div>
        <!-----------begin menu--------------->
        <script type="text/ecmascript" language="javascript">
			$(document).ready(function(){
			
				var a=0;
				if(a==0){
				$('.subpage_menu_move').click(function(){				
					$(this).children('.subpage_menu_down').slideToggle();				
					})
					a=1;
				}
				else{
				$('.subpage_menu_move').click(function(){
					$('.subpage_menu_down').hide();
					})
					a=0;
				}
				})
        </script>
        
        <!-----------end menu--------------->       
     
    </div>
        <!-----------end header-------------->
         <!-----------begin main-------------->
       <div id="subpage_home">
       		<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/home.png" />  <a href="<?php echo $this->baseUrl();?>">Home</a> > Subpage
       </div>
    <div id="subpage_wapper">
    	<div class="subpage_wapper_left_detail">
    		<?php echo $this->layout()->content;?>
        </div>
    	<div class="subpage_wapper_right">
        	<div id="news">
            	<div class="news_title">
                	<p onclick="toggle_view('col1','col2');" class="news1">Mới nhất</p>
                    <p onclick="toggle_view('col2','col1');" class="news2">Đọc nhiều nhất</p>
                </div>
                <span id="col1">
	                <ul>
	                	<li><a href="#">Duesseldorf - Bayern: Xác lập kỷ lục? </a></li>
	                    <li><a href="#">Giải thưởng văn học: Không đơn thuần là vinh danh tác phẩm.</a></li>
	                    <li><a href="#">Người hâm mộ vẫn đang chờ "bữa tiệc bóng đá" của ĐT Việt Nam </a></li>
	                    <li><a href="#">Liverpool - Reading: Dài cổ chờ chiến thắng ở Anfield</a></li>
	                    <li><a href="#">Norwich City - Arsenal: Không còn dễ tổn thương khi xa Emirates</a></li>
	                    <li><a href="#">Giải taekwondo quân sự thế giới: Việt Nam hy vọng nội dung quyền.</a></li>
	                    <li><a href="#">Giải thưởng văn học: Không đơn thuần là vinh danh tác phẩm.</a></li>
	                </ul>
	                <p class="read_add"><a href="#">Xem thêm</a></p> <br clear="both" />
                </span>
                <span id="col2" style="display:none">
	                <ul>
	                	<li><a href="#">Norwich City - Arsenal: Không còn dễ tổn thương khi xa Emirates</a></li>
	                    <li><a href="#">Giải taekwondo quân sự thế giới: Việt Nam hy vọng nội dung quyền.</a></li>
	                    <li><a href="#">Giải thưởng văn học: Không đơn thuần là vinh danh tác phẩm.</a></li>
	                	<li><a href="#">Duesseldorf - Bayern: Xác lập kỷ lục? </a></li>
	                    <li><a href="#">Giải thưởng văn học: Không đơn thuần là vinh danh tác phẩm.</a></li>
	                    <li><a href="#">Người hâm mộ vẫn đang chờ "bữa tiệc bóng đá" của ĐT Việt Nam </a></li>
	                    <li><a href="#">Liverpool - Reading: Dài cổ chờ chiến thắng ở Anfield</a></li>
	                </ul>
	                <p class="read_add"><a href="#">Xem thêm</a></p> <br clear="both" />
                </span>
            </div>
            <div id="news" class="bgnews">
            	<div class="news_title2">
                	Forum
                </div>
                <ul>
                	<li><a href="#">Duesseldorf - Bayern: Xác lập kỷ lục? </a></li>
                    <li><a href="#">Giải thưởng văn học: Không đơn thuần là vinh danh tác phẩm.</a></li>
                    <li><a href="#">Người hâm mộ vẫn đang chờ "bữa tiệc bóng đá" của ĐT Việt Nam </a></li>
                    <li><a href="#">Liverpool - Reading: Dài cổ chờ chiến thắng ở Anfield</a></li>
                    <li><a href="#">Norwich City - Arsenal: Không còn dễ tổn thương khi xa Emirates</a></li>
                    <li><a href="#">Giải taekwondo quân sự thế giới: Việt Nam hy vọng nội dung quyền.
</a></li>

                </ul>
                <p class="read_add"><a href="#">Xem thêm</a></p>
                <br clear="both" />
            </div>
              <div id="news" class="bgnews2">
            	<div class="news_title2">
                	Ảnh đẹp
                </div>
                <ul>
                	<li  class="even"><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/1.gif" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/2.gif" /></a></li>
                    <li  class="even"><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/3.gif" /></a></li>
                    <li ><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/4.gif" /></a></li>
                    <li class="even"><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/5.gif" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/6.gif" /></a></li>
</a></li>

                </ul>
                <p class="read_add"><a href="#">Xem thêm</a></p>
                <br clear="both" />
            </div>
			<div id="ads-right">
				Ads Right
			</div>
        </div>      

    </div><br clear="both" />
     <!-----------end main-------------->
    <div id="subpage_footer">
    	<div id="subpage_footer_top"></div>
        <div id="subpage_footer_bottom">
        	<div class="content_subpage_footer_bottom">
                <div class="ul_footer" id="ul1">
                    <ul class="ul1">
                        <li><a href="#">Tin tức</a></li>
                        <li><a href="#">Văn Miếu</a></li>
                        <li><a href="#">Võ Miếu</a></li>
                        <li><a href="#">VHTT Unesco</a></li>
                        <li><a href="#">Liên hệ</a></li>
                        <li><a href="#">Quảng cáo</a></li>
                    </ul>
                </div>
                <div class="ul_footer" id="ul2">
                    <ul class="ul2">
                        <li><a href="#" style="color:#a9a9a9">Địa chỉ</a></li>
                        <li><a href="#">123, street name landmark,California 123</a></li>
                        <li><a href="#">Tel: 123-456-7890</a></li>
                        <li><a href="#">Fax. +123-456-7890</a></li>                 
                      
                    </ul>
                </div>
                  <div class="ul_footer" id="ul3">
                   	<ul>
                    	<li><a href="#" style="color:#a9a9a9"> Liên hệ Quảng cáo</a></li>
                        <li><a href="#">Proin enim velit, fermentum at malesuada in, porta vel ipsum. Pellentesque a erat sit amet lorem rutrum venenatis sed laoreet dui.</a></li>
                    </ul>
                </div>
                <div class="ul_footer" id="ul4">
                    <ul>
                        <li><a href="#" style="color:#a9a9a9">Social Network</a></li>
                        <li><a href="#">Find us on these social network sites</a></li>
                        <li>
                        	<ul id="img_footer">
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/fab.gif" /></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/tiw.png" /></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/as.gif" /></a></li>
                            </ul>
                       </li>                       
                    </ul>
                </div>
             </div>
        </div>
         <div id="copy">
             	<p>Copyright © 2012 UNC. Designed by vanveo</p>
             </div>
    </div>
</body>
</html>
