<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headScript();?>
<link type="text/css" href="<?php echo $this->baseUrl();?>/application/templates/front/css/style.css" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl();?>/application/templates/front/themes/2/js-image-slider.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl();?>/application/templates/front/themes/2/js-image-slider.js" type="text/javascript"></script>
 <link href="<?php echo $this->baseUrl();?>/application/templates/front/generic.css" rel="stylesheet" type="text/css" />
<title>UNC</title>
</head>

<body>
<div>
	<!------------begin header-------------->
	<div id="header">
    	<div id="logo"> <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.png"></div>
        <div id="right-header">
        	<div id="right-header1"></div>
            <div class="right-header2"><div class="img-header"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_09.png"></div><p>12/8/2012 Khai giảng lớp liên thông vp2</p></div>
            <div class="right-header2"><div class="img-header"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_03.png"></div><p>Chuột không giây Amition GIẢM <label>20%</label> giá sốc</p></div>
            <div class="right-header2"><div class="img-header"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_12.png"></div><p>Bạn đang đi làm? Bạn chưa có bằng đại học</p></div>
        </div>
    </div>
    <!------------end header-------------->
    
    <!------------begin content-------------->
    <div id="content">
    	<!----------------begin-menu------------>
        <div id="top-menus">
        	<div><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_23.png" width="1000px" height="20px"/></div>
            <div id="top-menu">
            	<ul id="nav">
                	<li class="color-menu" id="home"><a href="<?php echo $this->baseUrl();?>"><div style="margin:7px 5px 0 30px; float:left"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/home.png"/></div> Tin tức</a></li><li></li>
                	  <?php foreach($this->listParent as $parent)
					  {
					  ?>
                    <li class="top"><a href="<?php echo $this->baseUrl(); ?>/tintuc/list/categoryId/<?php echo $parent['category_id']; ?>"><span> <?php echo $parent['category_name'] ?><!--Lấy ra danh mục cha--></span></a>
                    	<ul class="sub">     
                        		<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                            		<li><a href="<?php echo $this->baseUrl(); ?>/tintuc/list/categoryId/<?php echo $child['category_id']; ?>"><?php echo $child['category_name']; ?></a></li></br>
                            	<?php
									}
								}
                            	?>                   	
                        </ul>
                    </li><li>|</li>
                    <?php }?>
                    <li><a href="#">Video</a></li><li>|</li>
                    <li><a href="#">Forum</a></li>
                    
                </ul>
            </div>
        </div>
       	<!----------------end-menu------------>
        
        <!----------------begin-maincontent------------>
        <!----------------begin-slide------------>
    <div id="left-slide">
    <div id="sliderFrame">
        <div id="slider">
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-2.jpg" alt="Hello!!!" />
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-3.jpg" />
            <img src="<?php echo $this->baseUrl();?>/application/templates/front/images/image-slider-4.jpg" />
        </div>
        <!--thumbnails-->               	
        <div id="thumbs">
        	        <?php 
                    foreach($this->listHotNewsJs as $news)
					{
					?>
            <div class="thumb">
                <div class="thumb-content"><p><?php echo $news['news_title']; ?></p></div>
                <div style="clear:both;"></div>
            </div>
            		<?php
					}
                    ?>
           </div>

        <!--clear above float:left elements. It is required if above #slider is styled as float:left. -->
        <div style="clear:both;height:0;"></div>
    </div>
    </div>
<!-- End slider-->
<div id="right-slide">
                	<div id="rsl-1">
                    	<div id="rs1"><div id="img"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_39.png" width="13" height="13"/></div>
                    		<p onclick="toggle_view('col1','col2');">Nóng nhất</p>
                    	</div>
                        <div id="rs2" onclick="toggle_view('col2','col1');"><p>Đọc nhiều nhất</p></div>
                    </div>
                    
                   <div id="col1">
                    <?php 
                    foreach($this->listHotNews as $news)
					{
						?>
							<div class="risl-2"><a href="<?php echo $this->baseUrl(); ?>/tintuc/detail/newsid/<?php echo $news['news_id']; ?>">
								<?php 
									$charset = 'utf-8';
									$len = 45;
									$string = $news['news_title']; 
									$string = html_entity_decode($string, ENT_QUOTES, $charset);
									if(mb_strlen($string, $charset)> $len)
									{
										$arr = explode(' ', $string);
										$string = mb_substr($string, 0, $len, $charset);
										$arrRes = explode(' ', $string);
										$last = $arr[count($arrRes)-1];
									
										unset($arr);
										if(strcasecmp($arrRes[count($arrRes)-1], $last))
										{
											unset($arrRes[count($arrRes)-1]);
										}
										$string = implode(' ', $arrRes)."...";
									}
									echo $string;
								?></a></div>
						<?php
					}
                    ?>
                    </div>
                    
                    <div id="col2" style="display:none">
                    <?php 
                    foreach($this->listNewsMostView as $news)
					{
						?>
							<div class="risl-2"><a href="<?php echo $this->baseUrl(); ?>/tintuc/detail/newsid/<?php echo $news['news_id']; ?>">
								<?php 
									$charset = 'utf-8';
									$len = 45;
									$string = $news['news_title']; 
									$string = html_entity_decode($string, ENT_QUOTES, $charset);
									if(mb_strlen($string, $charset)> $len)
									{
										$arr = explode(' ', $string);
										$string = mb_substr($string, 0, $len, $charset);
										$arrRes = explode(' ', $string);
										$last = $arr[count($arrRes)-1];
									
										unset($arr);
										if(strcasecmp($arrRes[count($arrRes)-1], $last))
										{
											unset($arrRes[count($arrRes)-1]);
										}
										$string = implode(' ', $arrRes)."...";
									}
									echo $string;
								?></a></div>
						<?php
					}
                    ?>
                    </div>

        <!--clear above float:left elements. It is required if above #slider is styled as float:left. -->
        <div style="clear:both;height:0;"></div>
    </div>
            <div id="note-slide">
            	<div id="text-slide">
                	<p class="tieude">Những sai lầm dễ mắc phải khi tập luyện</p>
                    <p>Hệ thống ngũ hình quyền với 5 con linh thú (Long, Hổ, Báo, Xà, Hạc) nằm trong chương trình luyện tập của một số dòng phái Vịnh Xuân quền tại Hà Nội, Việt Nam như Vĩnh Xuân Nội gia quyền, Vĩnh Xuân Ngô gia Hoàng pháp và hiện cũng đã được tập luyện tại Thành Phố Hồ Chí Minh.<br/> Không ai biết chính xác hệ thống này bắt đầu từ khi nào, nhưng chắc chắn nó có nguồn gốc từ Thiếu Lâm Tự. Rất có thể xuất phát từ Bạch Ngọc Phong đời nhà Nguyên Trung Hoa, khi ông nương theo bài La Hán Thập Bát Thủ gồm 18 thế tay của vị Phật A La Hán của Thiếu Lâm để chế ra Ngũ Hình quyền gồm các bài quyền dựa theo những con thú nói trên và một bài tổng hợp của 5 con thú.<br/> Sau này trải qua một tiến trình lịch sử dằng dặc, hệ thống ngũ hình đã được trau truốt, tinh lọc, sửa đổi rất nhiều. Đáng chú ý là sự bổ sung của hệ thống này vào kỹ pháp các dòng phái Vịnh.</p>
                    <div>
                    	<div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg"/>
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg" />
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg"/>
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                        <div class="imtext-slide">
                        	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_48.jpg" />
                            <div class="color-bg">Thứ 2,<br/> ngày 9/12/2012</div>
                        </div>
                    </div>
                </div>
                <div id="rua-images">
                	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/RUA.png" />                    
                </div>
            </div>
        </div>
        <!---------------end slide------------>
        <!---------------begin ads----------->
        <div id="ads">
        	<div id="left-ads">
            	<div id="tittle-adds">
                	<div id="logo-ads"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logoads.png"/></div>
                    <div id="tittles">
                    	<p id="p1">Lớp chia sẻ kinh nghiệm, kỹ năng thực tế:</p>
                        <p id="p2">Để làm việc tại Ngân Hàng</p>
                    </div>
                </div>
                <ul id="text-ads">
                	<li>Cung cấp các kỹ năng mềm, kỹ năng vượt qua cuộc phỏng vấn của nhà tuyển dụng và các bài tập tình huống: Phát triển năng lực và nguyện vọng của mỗi người đối với mỗi vị trí công việc cụ thể;</li>
                    <li> Nhận biết những rủi ro trong hoạt động nghề nghiệp, phương pháp vượt qua những rủi ro trong mọi lĩnh vực nhạy cảm như: hoạt động, tín dụng, hoạt động giao dịch, hoạt động thanh toán, ngân quỹ...</li>
                </ul>
            </div>
          	<div id="right-ads">
            	<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/NEN_52.png"/>
            </div>
        </div>
        <!---------------end ads----------->
        
        <!---------------begin news---------->
        <div id="main-content">
        	<!------------begin tin tức------->
        	 <div id="news">
                
                <?php echo$this->layout()->content;?>
                
            </div>
            
            <!------------end tin tức------->
            <!------------begin video------->
            <div id="video">
            	<div id="tube">
                	<div id="vd">Video Clip</div>
                	<object width="300" height="230" style="margin-left:15px;"><param name="movie" value="http://www.youtube.com/watch?v=syPTDwFwEkk&feature=relmfu"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/watch?v=syPTDwFwEkk&feature=relmfu" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300" height="230"></embed></object>


                </div>
                <?php
                       		foreach($this->listquangcao as $quangcao)
								{
									
                        		?>
                <div class="img-tube"><a href="<?php echo $quangcao['ads_link']; ?>" target="_blank">   <?php echo $quangcao['ads_banner']; ?></a></div>
                <?php   } ?>
            </div>
            <!------------end video------->
        </div>
       
        <!---------------end news----------->
        
        <!----------------end-maincontent------------>
    </div>
    <!------------end content-------------->
    
    <!------------begin footer-------------->
    <div id="footer">
    	<div id="search-footer">
        	<form class="form" action="<?php echo $this->baseUrl();?>/timkiem" name="search-form" method="post">
            	<input type="text" value="" name="search-text" style="background:url(images/search.png) no-repeat; background-color:#FFF; padding-left:20px" />
            	<input type="submit" name="submit" value="Tìm kiếm" />
            </form>
        </div>
        <div id="menu-footer">
        	<ul>
            		<li><a href="<?php echo $this->baseUrl();?>"> Tin tức</a></li><li>|</li>
					<?php foreach($this->listParent as $parent)
					  {
					  ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/tintuc/list/categoryId/<?php echo $parent['category_id']; ?>"><span> <?php echo $parent['category_name'] ?><!--Lấy ra danh mục cha--></span></li></a><li>|</li>
					<?php } ?>
                    <li><a href="#">Video</a></li><li>|</li>
                    <li><a href="#">Forum</a></li></li>
            </ul>
        </div>
        <div id="copyright">Địa chỉ: Tòa nhà CT5B - Mễ Trì Thượng - Từ Liêm - Hà Nội. Điện thoại: (+84) 85898964. Email: support@niw.com.vn<br/><br/>© Copyright NIW – Công ty TNHH Công nghệ phần mềm - Design by <a href="http://niw.com.vn/">NIW</a></div>
    </div>
    <!------------end footer-------------->
</div>
</body>
</html>
