<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle() ?>

	<!------------script-------------->
<div style="abc">
    <div id="divAdRight" style="DISPLAY: none; POSITION: absolute; TOP: 0px">
	                <?php
	                       		foreach($this->listquangcao4 as $quangcao)
									{
	                        		?>
	                <div class="img-ads-scrol">
	                	<center>
	                		<a href="<?php echo $quangcao['ads_link']; ?>" target="_blank">   <?php echo $quangcao['ads_banner']; ?></a>
	                	</center>	
	                </div>
	                <?php   } ?>    
    </div>
</div>
    <div id="divAdLeft" style="DISPLAY: none; POSITION: absolute; TOP: 0px">
	                <?php
	                       		foreach($this->listquangcao3 as $quangcao)
									{
	                        		?>
	                <div class="img-ads-scrol">
	                	<center>
	                		<a href="<?php echo $quangcao['ads_link']; ?>" target="_blank">   <?php echo $quangcao['ads_banner']; ?></a>
	                	</center>	
	                </div>
	                <?php   } ?>    
    </div>

    <script>
        function FloatTopDiv()
        {
            startLX = ((document.body.clientWidth -MainContentW)/2)-LeftBannerW-LeftAdjust , startLY = TopAdjust+80;
            startRX = ((document.body.clientWidth -MainContentW)/2)+MainContentW+RightAdjust , startRY = TopAdjust+80;
            var d = document;
            function ml(id)
            {
                var el=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
                el.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
                el.x = startRX;
                el.y = startRY;
                return el;
            }
            function m2(id)
            {
                var e2=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
                e2.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
                e2.x = startLX;
                e2.y = startLY;
                return e2;
            }
            window.stayTopLeft=function()
            {
                if (document.documentElement && document.documentElement.scrollTop)
                    var pY =  document.documentElement.scrollTop;
                else if (document.body)
                    var pY =  document.body.scrollTop;
                if (document.body.scrollTop > 30){startLY = 3;startRY = 3;} else {startLY = TopAdjust;startRY = TopAdjust;};
                ftlObj.y += (pY+startRY-ftlObj.y)/16;
                ftlObj.sP(ftlObj.x, ftlObj.y);
                ftlObj2.y += (pY+startLY-ftlObj2.y)/16;
                ftlObj2.sP(ftlObj2.x, ftlObj2.y);
                setTimeout("stayTopLeft()", 1);
            }
            ftlObj = ml("divAdRight");
            //stayTopLeft();
            ftlObj2 = m2("divAdLeft");
            stayTopLeft();
        }
        function ShowAdDiv()
        {
            var objAdDivRight = document.getElementById("divAdRight");
            var objAdDivLeft = document.getElementById("divAdLeft");       
            if (document.body.clientWidth < 1000)
            {
                objAdDivRight.style.display = "none";
                objAdDivLeft.style.display = "none";
            }
            else
            {
                objAdDivRight.style.display = "block";
                objAdDivLeft.style.display = "block";
                FloatTopDiv();
            }
        } 
    </script>
    <script>
    document.write("<script type='text/javascript' language='javascript'>MainContentW = 1030;LeftBannerW = 125;RightBannerW = 125;LeftAdjust = 1;RightAdjust = -10;TopAdjust = 10;ShowAdDiv();window.onresize=ShowAdDiv;;<\/script>");
    </script>
		<!------------begin Script-------------->
		
<link href="<?php echo $this->baseUrl();?>/application/templates/front/css/style.css" type="text/css" rel="stylesheet" />
<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/front/js/switch_news.js" type="text/javascript"></script>
</head>

<body>
	 <!-----------begin header-------------->
	<div id="header">
    	<div id="center-header">
        	<div id="subpage_logo"><a href="<?php echo $this->baseUrl();?>"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/logo.gif"/></a></div>
            <div id="subpage_search">
            	<form class="search-form" action="<?php echo $this->baseUrl();?>/timkiem" method="post">
					<input name="search-text" class="t" onfocus="if (this.value == 'Tìm kiếm …') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Tìm kiếm …';}" type="text" value="Tìm kiếm …"/>
					<input class="searchsubmit" type="submit" value="" style="cursor:pointer"/>
				</form>
            </div>
            <div id="top-ad" style="margin-top:10px">
            	<a href="<?php echo $this->listquangcao1['ads_link']; ?>" target="_blank">
                	<?php echo $this->listquangcao1['ads_banner']; ?>
                </a>
            </div>
            			<!--------Menu-Top------>
			<div id="menu-top">
				<ul id="nav">
					<?php foreach($this->listParent as $parent)
					  {
					  ?>
					  	<li class="item ">
				            <a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $parent['category_id']; ?>-1-<?php echo $parent['alias']; ?>.html"><?php echo $parent['category_name'] ?></a>
				            <ul class="sub">
								<?php
                        		foreach($this->listChild as $child)
								{
									if($child['category_parent_id'] == $parent['category_id'])
									{
                        		?>
                        			<li class="itemSub">
					                    <a class="a-style" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $child['category_id'];?>-1-<?php echo $child['alias'];?>.html"><?php echo $child['category_name']; ?></a>
					                </li>
					                <li class="itemSub">|</li>
                        		<?php } 
									}?>
				            </ul>
				        </li>
					  <?php }?>
			        <li class="item">
			            <a href="<?php echo $this->baseUrl(); ?>/video/danh-sach/1-trang.html">Video</a>
			        </li>
			        <li class="item">
			            <a href="<?php echo $this->baseUrl(); ?>/forum/forum.php">Forum</a>
			        </li>
			    </ul>
       </div>
        <!-----------end menu---------------> 	          
        </div>
        <!-----------begin menu--------------->
        <script type="text/ecmascript" language="javascript">
			$(document).ready(function(){
			
				var a=0;
				if(a==0){
				$('.subpage_menu_move').click(function(){				
					$(this).children('.subpage_menu_down').slideToggle();				
					})
					a=1;
				}
				else{
				$('.subpage_menu_move').click(function(){
					$('.subpage_menu_down').hide();
					})
					a=0;
				}
				})
        </script>
        
        <!-----------end menu--------------->       
     
    </div>
        <!-----------end header-------------->
         <!-----------begin main-------------->
       <div id="subpage_home">
       		<img src="<?php echo $this->baseUrl();?>/application/templates/front/images/home.png" />  <a href="<?php echo $this->baseUrl();?>">Home</a><?php if (isset($this->current_category)) echo ' > '.$this->current_category['category_name']?>
       </div>
    <div id="subpage_wapper">
    	<div class="subpage_wapper_left_detail">
    		<?php echo $this->layout()->content;?>
        </div>
		<?php 
			if($_SESSION['page'] == 'tintuc')
				echo $this->render("tintuc.phtml");
			if($_SESSION['page'] == 'hinhanh')
				echo $this->render("hinhanh.phtml");  
		?>
     <!-----------end main-------------->
    <div id="subpage_footer">
    	<div id="subpage_footer_top"></div>
        <div id="subpage_footer_bottom">
        	<div class="content_subpage_footer_bottom">
                <div class="ul_footer" id="ul1">
                    <ul class="ul1">
                    	<?php foreach($this->listParent as $parent)
						  {
						  ?>
	                    <li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $parent['category_id']; ?>-1-<?php echo $parent['alias']; ?>.html"><span> <?php echo $parent['category_name'] ?><!--Lấy ra danh mục cha--></span></a></li>
						<?php } ?>
                    </ul>
                </div>
                <div class="ul_footer" id="ul2">
                    <ul class="ul2">
                        <li><a href="#" style="color:#a9a9a9">Địa chỉ</a></li>
                        <?php 
                        foreach ($this->listdiachi as $listdiachi) {
                        ?>
                        <li>Địa chỉ: <?php echo $listdiachi['address'] ?> </li>
                        <?php } ?>
                      
                    </ul>
                </div>
                  <div class="ul_footer" id="ul3">
                   	<ul>
                    	<li><a href="#" style="color:#a9a9a9"> Liên hệ Quảng cáo</a></li>
                    	<?php 
                        foreach ($this->listdiachi as $listdiachi) {
                        ?>
                        <li><?php echo $listdiachi['contact'] ?> </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="ul_footer" id="ul4">
                    <ul>
                        <li><a href="#" style="color:#a9a9a9">Social Network</a></li>
                        <li>Find us on these social network sites</li>
                        <li>
                        	<ul id="img_footer">
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/fab.gif" /></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/tiw.png" /></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl();?>/application/templates/front/images/as.gif" /></a></li>
                            </ul>
                       </li>                       
                    </ul>
                </div>
             	<br style="clear:both"/>
             </div>
        </div>
         <div id="copy">
             	<p>Copyright © 2012 UNC. Designed by UNC</p>
             </div>
    </div>
</body>
</html>
