MSGHome = {
	"MUST_INPUT_TITLE" : "Vui lòng nhập tiêu đề!",
	"MUST_INPUT_CORRECT_EMAIL" : "Vui lòng nhập vào email hợp lệ",
	"MUST_INPUT_NUMBER" : "Vui lòng nhập số.",
	"LENGTH_PHONE_10" : "Độ dài của số điện thoại phải bằng 10.",
	"CAPTCHA_REQUIRE" : "Vui lòng nhập hoặc nhập sai mã an toàn.",
	"PHONE_FORMAT_REQUIRE" : "Vui lòng vào định dạng như sau của số điện thoại(xxx)xxx-xxxx."
};

MSGArticle ={
	"VALUE":"Giá trị ",
	"NONBLANK":" không được để trống",
	"NONNUMBER":" không phải là một số",
	"GTZERO":" phải lớn hơn 0",
	"EMAIL_NON_CORRECT":"Giá trị email bạn nhập vào không đúng",
	"EMAIL_TITLE": "tiêu đề",
	"EMAIL_BODY": "nội dung",
	"CAPTCHA":"mã an toàn",
	"CAPTCHA_NON_CORRECT": "Mã an toàn bạn nhập vào chưa đúng.",
	"EMAIL_NAME_SENDER" : "Tên người gửi",
	"EMAIL_SENDER":"Email người gửi",
	"EMAIL_NAME_RECIEVER":"Tên người nhận",
	"EMAIL_RECEIVER":"Email người nhận"
};

MSGCity = {
	"VIEW_MORE":"Xem thêm các tỉnh thành khác",
	"VIEW_LESS": "Ẩn bớt các tỉnh thành phố"
};

MSGUtility = {
	"HOME_WIDTH": "chiều rộng nhà",
	"HOME_LENGTH": "chiều dài nhà",
	"HOME_NUM_FLOOR": "số tầng nhà",
	
	"YEAR_NON_BLANK": "Năm sinh gia chủ không được để trống.",
	"YEAR_MUST_GT": "Năm sinh gia chủ phải nhỏ hơn năm dự kiến xây nhà!!!",
	"LET_INPUT_TEXT": "Vui lòng nhập số vào trong textbox.",
	"INPUT_YEAR_YYYY": "Vui lòng nhập năm có 4 chữ số.",
	"YEAR_GT_1990": "Năm sinh phải >=1900.",
	
	"MONEY_NON_BLANK": "Số tiền vay không được để trống!",
	"TIME_NON_BLANK":"Thời gian vay không được để trống!",
	"PRODUCT_NON_BLANK":"Lãi suất không được để trống!",
	"TIME_AT_LEAST": "Thời gian vay  tối thiểu là 1 tháng và tối đa là 1200 tháng.\r\n Xin vui lòng nhập lại thời gian vay của quý khách.",
	"TIME_AT_LEAST_YEAR": "Thời gian vay  tối thiểu là 1 năm và tối đa là 100 năm.\r\n Xin vui lòng nhập lại thời gian vay của quý khách.",
	"MONEY_AT_LEAST":"Số tiền vay tối thiểu là 10,000,000 VND, xin vui lòng nhập lại lượng tiền vay ."

};

MSGProduct = {
	"COMPLAIN_NOT_CHOOSE":"Vui lòng chọn lý do than phiền",
	"FIELD_MUST_INPUT":"Các trường (*) là bắt buộc phải nhập!",
	"NAME_BLANK":"Vui lòng nhập họ tên!",
	"EMAIL_BLANK":"Vui lòng nhập địa chỉ email!",
	"ASK_BLANK":"Vui lòng nhập nội dung muốn hỏi!!",
	"REMOVE_ADVANCE_SEARCH": "Bỏ tìm kiếm nâng cao",
	"ADVANCE_SEARCH":"Tìm kiếm nâng cao",
	"CATEGORY_NOT_CHOOSE":"Vui lòng chọn chuyên mục",
	"PRODUCT_NOT_CHOOSE":"Vui lòng chọn loại bất động sản"
};

MSGQuestion = {
	"BODY_BLANK":"Vui lòng nhập nội dung!",
	"QUESTION_BLANK":"Vui lòng nhập câu hỏi!",
	"MUST_SELECT_MAIN_CAT":"Vui lòng chọn chuyên mục chính!",
	"MUST_SELECT_SUB_CAT":"Vui lòng chọn chuyên mục con!",
	"MUST_INPUT_NAME":"Vui lòng nhập tên liên hệ."
};

MSGUser = {
    "EMAIL_NOT_AVAILABLE": "<br/>Email này đã có người sử dụng!",
	"SAVE_CHANGE":"Bạn muốn lưu thay đổi?",
	"ERROR_OCCUR":"Có lỗi xảy ra: ",
	"BDS_TYPE": "Loại BĐS",
	"CITY": "Thành phố",
	"DISTRICT": "Quận/huyện",
	"PROJECT":"Dự án",
	"CHOOSE":"--Chọn--",
	"DELETE":"Xóa",
	"LINE":"Line ",
	"CHOOSE_BDS":" phải chọn loại BDS",
	"CHOOSE_CITY": " phải chọn thành phố",
	"VALUE_BLANK":"Bạn đang để giá trị trống",
	"ERROR_RETRY":"Có lỗi xảy ra trong quá trình cập nhật thông tin cá nhân của bạn.<br/>Xin vui lòng thử lại sau.",
	"UPDATE_INFO_SUCCESS":"Cập nhật thông tin giới thiệu thành công.",
	"SOME_ERROR":"Có một số lỗi dưới đây:",
	"BROKER_NAME_BLANK":"Vui lòng nhập tên nhà môi giới",
	"COMPANY_NAME_BLANK":"Vui lòng nhập tên doanh nghiệp",
	"UPDATE_PRIVATE_SUCCESS":"Cập nhật thông tin cá nhân thành công",
	"ADDRESS":"Địa chỉ:",
	"ACCURANCY":"Độ chính xác:",
	"NOT_FOUND":"Không tìm thấy",
	"NOT_DEFINE":"Không xác định",
	"OLD_PASSWORD":"Mật khẩu cũ",
	"NEW_PASSWORD":"Mật khẩu mới",
	"GT_6_CHARACTER":">= 6 ký tự",
	"LT_16_CHARACTER": "<= 16 ký tự",
	"VERIFY":"Xác nhận",
	"PASS_INCORRECT":"Sai mật khẩu",
	"CORRECT_VALUE":"Giá trị hợp lệ",
	"PASS_UPDATE_SUCC":"Cập nhật mật khẩu thành công!",
	"ERROR_OCCUR":"Có lỗi xảy ra. <br /> Chi tiết: ",
	"RIGHT":"Hợp lệ",
	"INCORRECT":"Sai",
	"LACK":"Thiếu",
	"DELETE_MEMBER_VERIFY":"Bạn muốn xóa thành viên này?",
	"AGGREE":"Đồng ý",
	"CANCEL":"Hủy",
	"DELETE_ARTICLE_VERIFY":"Bạn có muốn xóa bài viết này không?",
	"THE_LENGTH":"Độ dài của ",
	"MUST_GT":" phải lớn hơn ",
	"CHARACTER":" kí tự.",
	"CHOOSE_DISTRICT":"--Chọn Quận/Huyện--",
	"CHOOSE_PRJ":"--Chọn Dự án--",
	"CHOOSE_TYPE":"--Chọn loại--",
	"MUST_INPUT_BRANCH_NAME":"Vui lòng nhập tên chi nhánh",
	"BRANCH_NAME_GT16":"Tên chi nhánh tối thiểu 16 ký tự",
	"BRANCH_NAME_LT200":"Tên chi nhánh không quá 200 ký tự",
	"MUST_CHOOSE_CITY":"Vui lòng chọn Tỉnh / Thành phố",
	"MUST_CHOOSE_DISTRICT":"Vui lòng chọn Quận/Huyện",
	"MUST_INPUT_PHONE":"Vui lòng nhập điện thoại",
	"MUST_INPUT_NUMBER":"Vui lòng nhập số.",
	"NUMBER_NOT_EXIST":"Số điện thoại không tồn tại ở VN!",
	"MOBILE_NUMBER_NOT_EXIST":"Số di động không tồn tại ở VN!",
	"BRANCH_ADD_SUCC":"Đã thêm chi nhánh thành công",
	"ACCEPT_VALUE":"Giá trị hợp lệ",
	"DELETE_NEWS_VERIFY":"Bạn muốn xóa tin này?",
	"DELETE_ARTICLE_SUCC":"Đã xóa bài viết thành công",
	"SAVE_YOUR_POST":"Đã lưu cấu hình tin của bạn!",
	"ERROR_DETAIL":"Có lỗi xảy ra! Chi tiết: ",
	"MUST_INPUT_TITLE":"Vui lòng nhập tiêu đề tin",
	"MUST_LT_100":"Tiêu đề không quá 100 ký tự",
	"MUST_INPUT_CONTENT":"Vui lòng nhập nội dung",
	"MUST_CHOOSE_TYPE_BDS":"Vui lòng chọn hình thức BĐS",
	"MUST_CHOOSE_KIND_BDS":"Vui lòng chọn loại BĐS",
	"MUST_CHOOSE_POST_DATE":"Vui lòng chọn ngày đăng tin",
	"MUST_CHOOSE_END_DATE":"Vui lòng chọn ngày hạ tin",
	"MUST_INPUT_PHONE_CONTACT":"Vui lòng nhập số ĐT liên hệ",
	"PHONE_NUMBER_INCORRECT":"Số điện thoại không đúng",
	"PHONE_TOO_SHORT":"Số điện thoại của bạn quá ngắn",
	"PHONE_TOO_LONG":"Số điện thoại của bạn quá dài",
	"NEED_EDIT":"Bạn có cần sửa gì nữa không?",
	"MUST_INPUT_CAPTCHA":"Vui lòng nhập mã an toàn",
	"DONT_WANT_POST_NEWS":"Bạn không muốn đăng tin nữa?",
	"MUST_INPUT_INTRO":"Bạn vui lòng nhập giới thiệu",
	"MUST_CHOOSE":"Vui lòng chọn",
	"MUST_FILL":"Vui lòng nhập",
	"MUST_FILL_NUMBER":"Vui lòng nhập số, các số liền nhau, không có khoảng trắng hay ký tự ở giữa.",
	"MUST_GT_10":"Phải lớn hơn 10",
	"MUST_GT_0":"Phải lớn hơn 0",
	"MUST_GT_OR_EQUAL_0":"Phải >= 0",
	"TOO_SMALL":"Quá nhỏ",
	"TOO_BIG":"Quá lớn",
	"TOO_SHORT":"Quá ngắn",
	"TOO_LONG":"Quá dài",
	"MUST_DIFF_0":"Phải khác 0",
	"DEMAND_CITY":"Tỉnh thành phố",
	"DEMAND_DIST":"Quận huyện",
	"DEMAND_PRJ":"Dự án", 
	"DEMAND_AREA":"Diện tích", 
	"DEMAND_ROOM":"Số phòng",
	"DEMAND_BUY_PRICE":"Giá mua", 
	"DEMAND_ADD_CONTACT":"Địa chỉ liên hệ", 
	"DEMAND_NAME":"Họ và tên", 
	"DEMAND_PHONE":"Điện thoại cố định", 
	"DEMAND_MOBILE":"Điện thoại di động",
	"DEMAND_EMAIL":"Địa chỉ Email",
	"DEMAND_CATEGORY":"Chuyên mục", 
	"DEMAND_BDS":"Loại bất động sản", 
	"DEMAND_TITLE":"Tiêu đề tin",
	"DEMAND_CONTENT":"Nội dung", 
	"DEMAND_CAPTCHA":"Mã an toàn",
	"DEMAND_PHONE_INCORRECT":"Số điện thoại cố định của bạn không chính xác",
	"EMAIL_NOT_EXIST":"Địa chỉ Email của bạn không tồn tại",
	"ERROR_LIST":"Bạn quên nhập hoặc nhập sai các trường sau:\r\n(Chú ý:\r\n(1)\tCác trường có dấu (*) là trường bắt buộc phải nhập\r\n(2)\tCác giá trị nhập sai đã được bôi màu đỏ)\r\n",
	"SEND_VERIFY":"Chuẩn bị gửi bài, bạn chắc chắn không thay đổi gì nữa chứ?",
	"NEED_TO_VERIFY":"<p>Bài của bạn đã được gửi đến hệ thống để chờ kiểm duyệt.</p>",
	"ERROR_WAIT":"<p>Có lỗi phát sinh trong quá trình xử lý bài viết của bạn, vui lòng quay lại sau.</p>",
	"CHOOSE_IMAGE":"Chọn ảnh",
	"USER_NAME":"Họ tên",
	"USER_ADD":"địa chỉ",
	"USER_PHONE":"số điện thoại",
	"MONEY_NOT_ENOUGH":"Số tiền trong TK của bạn không đủ!",
	"NEED_CONFIRM_POST_NEWS":"Bạn muốn gửi tin ngay?",
	"NEED_SETTING_VIP":"Vui lòng xác định số ngày đăng tin và loại tin!",
	"CLOSE_BUTTON_TEXT":"Đồng ý",
	"EMPTY_TEXT":"&nbsp;",
	"PASS_BLANK":"Mật khẩu không được để trống.",
	"VALIDATE_DEMAND_FORM_1": "Có ",
	"VALIDATE_DEMAND_FORM_2": " lỗi trong dữ liệu của bạn. Vui lòng di chuột lên các vùng khoanh đỏ để xem thông báo lỗi.",
	"POST_DEMAND_TITLE"	: "Vui lòng nhập tiêu đề tin đăng của bạn. Tối đa 100 chữ.",
	"POST_DEMAND_CONTENT": "Vui lòng nhập nội dung tin đăng của bạn.",
	"POST_DEMAND_ADDRESS": "Vui lòng nhập địa chỉ bất động sản của bạn.",
	"POST_DEMAND_CONTACT_NAME": "Vui lòng nhập tên để người đọc tin có thể liên lạc với bạn.",
	"POST_DEMAND_CONTACT_ADD": "Vui lòng nhập địa chỉ để người đọc tin có thể liên lạc với bạn.",
	"POST_DEMAND_CAPTCHA": "Vui lòng nhập vào mã an toàn. Nhấn nút refresh để lấy mã an toàn khác.",
	"POST_DEMAND_AREA": "Vui lòng nhập tổng diện tích bất động sản.",
	"PASS_CONFIRM_NOT_EQUAL": "Mật khẩu không khớp nhau. Vui lòng nhập lại"	,
	"PASS_LENGTH_REQUIRE": "Mật khẩu của bạn phải dài từ 6 đến 16 kí tự",
	"NAME_LENGTH_REQUIRE": "Tên của bạn phải dài từ 2 đến 64 kí tự"
};

MSGScript = {
	"EMAIL_NOT_ACCEPT":"Email của bạn nhập không hợp lệ!",
	"MAXIMUM_INPUT":"Maximum value inputed!",
	"ERROR_CORRECT_REQUIRE":"You must correct all errors before save contact information!",
	"NOT_RECOGNIZE_OBJ":"Can not recognize object select box type!",
	"BDS_CHOOSE":"--Chọn loại BĐS--",
	"CITY_NOT_RECOGNIZE":"Can not recognize object select box cities!",
	"CITY_CHOOSE":"--Chọn Tỉnh/Thành--",
	"WANT_DEL_ACT":"Bạn muốn xóa lĩnh vực này?",
	"PRE_SEND":"Chuẩn bị gửi ...",
	"SENDING_POST_NUM":"Đang gửi cấu hình thứ: ",
	"SENT_POST":"Gửi xong cấu hình thứ: ",
	"SENT_WHOLE":"Đã gửi xong toàn bộ cấu hình đăng tin của bạn!",
	"POST_NUM":"Cấu hình thứ: ",
	"HAS_ERROR":" có lỗi.<br/>Chi tiết: TK của bạn không đủ!",
	"HAS_ERROR_DETAIL":" có lỗi.<br/>Chi tiết: "
}



