<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
		$(document).ready(function() {
			$('#listnews').dataTable({
				"sPaginationType": "full_numbers",
				"iDisplayLength": 25
			});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Thứ tự</th>
				<th>Danh mục</th>
				<th>Nội dung</th>
				<th>Liên kết</th>
				<th style="background:transparent">Sửa</th>
			</thead>
			<tbody>
				<?php 
				$count=1;
				foreach ($this->list as $item)
				{?>
					<tr>
						<td><?php echo $count;?></td>
						<td><?php echo $item['danhmuc'];?></td>
						<td><?php echo $item["noidung"];?></td>
						<td><?php echo $item["lienket"];?></td>
						<td><?php echo '<a href="'.$this->baseUrl().'/admin/diachi/edit/danhmuc/'.$item['danhmuc'].'" title="Sửa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
											?></td>
					</tr>
				<?php $count++;}?>
			</tbody>
		</table>
		
		<footer>
				<div class="submit_link" style="float:left; font-weight: bold;">
				</div>
		</footer>
	</div>
</article>