<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>

	<?php
	foreach ($this->list as $item)
	{?>
	 address: '<?php echo $item['address'];?>',
	 contact: '<?php echo $item['contact'];?>',
	 sua: 
		'<?php 
			echo '<a href="'.$this->baseUrl().'/admin/diachi/edit/address/'.$item['address'].'" title="Edit"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
		?>',
	 <?php
	}
	?> 


				
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
				<div class="submit_link" style="float:left; font-weight: bold;">
				</div>
		</footer>
	</div>
</article>