<?php if(count($this->listComment) > 0) { ?>
		<?php foreach($this->listComment as $comment) { ?>
				<p class="p_detail"><?php echo $comment['comment_name'] ?></p>
                <p><?php echo $comment['comment_time'] ?></p>
                <p><?php echo $comment['comment_content'] ?></p>
                <p style="text-align:right"><a href="#" onclick="return likeClick(<?php echo $comment['comment_id']?>);">Thích (<?php echo $comment['like']?>)</a> | <a href="#" onclick="return viphamClick(<?php echo $comment['comment_id']?>);">Báo cáo vi phạm (<?php echo $comment['vipham']?>)</a></p>
                <hr>
        <?php } ?>
<?php }?>