<?php if(count($this->comment) > 0) { ?>
		<?php foreach($this->comment as $comment) { ?>
			<p class="p_detail"><?php echo $comment['comment_name'] ?></p>
            <p><?php echo $comment['comment_time'] ?></p>
            <p><?php echo $comment['comment_content'] ?></p>
            <p style="text-align:right">
            	<a href="#" onclick="return likeClick(<?php echo $comment['comment_id']?>);">Thích (<?php echo $comment['like']?>)</a> 
            	| 
            	<a href="#" onclick="return viphamClick(<?php echo $comment['comment_id']?>);">Báo cáo vi phạm (<?php echo $comment['vipham']?>)</a>
            </p>
            <hr><?php } }?>