<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>

<script type="text/javascript">
	function checkall(class_name, obj){
		var items = document.getElementsByClassName(class_name);
		if(obj.checked == true){
			for(i=0;i<items.length;i++)
			items[i].checked = true;
		}
		else{
			for(i=0;i<items.length;i++)
			items[i].checked = false;
		}
	}
</script>
<form method="post" action="<?php echo $this->form->getAction();?>">

<script type="text/javascript">
//<!-----------Check all----->
functioheck(chk)
{
    // Nếu checkbox có tên checkAll được check
    if(document.fcheck.checkAll.checked==true){
        for (i = 0; i < chk.length; i++) // chạy vòng lặp để check tất cả
            chk[i].checked = true ;
    }else{
        for (i = 0; i < chk.length; i++) // chạy vòng lặp để uncheck tất cả
            chk[i].checked = false ;
    }
}
//<!-----------Check all----->
</script>
<?php if (isset($_SESSION['result']))
					{
						echo '<p class="message">';
						echo $_SESSION['result'];
						echo '</p>';
						unset($_SESSION['result']);
					}
					?>
<form method="post" name="fcheck" id="fcheck" action="<?php echo $this->form->getAction();?>">

	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset class="fieldset" style="float:left">
					<label>Tên đăng nhập</label>
					<?php echo $this->form->getElement('user_login');?>					
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Mật khẩu</label>
					<?php echo $this->form->getElement('user_pass');?>
				</fieldset>
				<fieldset class="fieldset" style="float:left">
					<label>Họ tên</label>
					<?php echo $this->form->getElement('user_fullname');?>
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Email</label>
					<?php echo $this->form->getElement('user_email');?>
				</fieldset>
				<fieldset class="fieldset" style="float:left">
					<label>Địa chỉ</label>
					<?php echo $this->form->getElement('user_address');?>
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Kích hoạt</label>
					<div style="margin-left: 84px;margin-top: -29px;">
						<?php echo $this->form->getElement('is_active');?>
					</div>
				</fieldset>
				<fieldset style="margin-left:-1px">
					<label style="width:300px">Các chuyên mục được phân quyền</label>
					<?php 
					foreach($this->listParent as $parent)
					{
					?>
						<div style="margin-left:50px;margin-bottom:10px">
							<input type="checkbox" name="check_object" onclick="checkall('item_<?php echo $parent['category_id'] ?>',this);"/>
							<span style="text-transform: uppercase"><?php echo $parent['category_name']; ?></span>
						</div>
						<?php
					$check = 0;
						//-------Chuyên mục cha-----
								foreach($this->listCategoryId as $categoryId)
									{
										
										if($categoryId['category_id'] == $parent['category_id'])
										{
											$check = 1; break;
										}
									}
								if($this->role == "0")
									{
										if($check == 1)
										{
											?>
												<input type="checkbox" name="checkbox[]" value="<?php echo $parent['category_id']; ?>" checked="checked"/>
												<span><?php echo $parent['category_name']; ?></span>
											<?php
										}
										else
										{
											?>
											<input type="checkbox" name="checkbox[]" value="<?php echo $parent['category_id']; ?>/>
											<p style="text-transform: uppercase;margin-left: 50px"><?php echo $parent['category_name']; ?></p>
											<?php
										}
									}
									else
									{
										if($check == 1)
										{
											?>
												<span><?php echo $child['category_name']; ?></span>
											<?php
										}
									}
									
									//-------End Chuyên mục cha-----
							foreach($this->listChild as $child)
							{
								$check = 0;
								if($child['category_parent_id'] == $parent['category_id'])
								{
									foreach($this->listCategoryId as $categoryId)
									{
										
										if($categoryId['category_id'] == $child['category_id'])
										{
											$check = 1; break;
										}
									}
									if($this->role == "0")
									{
										if($check == 1)
										{
											?>

											<div style="margin-left:100px">
												<input class="item_<?php echo $parent['category_id'] ?>" type="checkbox" name="checkbox[]" value="<?php echo $child['category_id']; ?>" checked="checked"/>
												<span><?php echo $child['category_name']; ?></span>
											</div>
												<br/>
											<?php
										}
										else
										{
											?>
											<div style="margin-left:100px">
												<input class="item_<?php echo $parent['category_id'] ?>" type="checkbox" name="checkbox[]" value="<?php echo $child['category_id']; ?>"/>
												<span><?php echo $child['category_name']; ?></span>
											</div>
												<br/>
											<?php
										}
									}
									else
									{
										if($check == 1)
										{
											?>
											<div style="margin-left:100px">
												<span><?php echo $child['category_name']; ?></span>
											</div>
												<br/>
											<?php
										}
									}
								}
							}
						?>
					<?php
					}
					?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/phongvien">Hủy bỏ</a>
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>