<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>Tên đăng nhập</th> 
	    				<th>Mật khẩu</th> 
	    				<th>Tên</th>
	    				<th>Email</th>
	    				<th>Địa chỉ</th>
	    				<th>Kích hoạt</th>
	    				<th>Tùy chọn</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{?>
				 		<tr>  
		    				<td><?php echo $item['user_login'];?></td> 
		    				<td><?php echo $item['user_pass'];?></td> 
		    				<td><?php echo $item['user_fullname'];?></td>
		    				<td><?php echo $item['user_email'];?></td>
		    				<td><?php echo $item['user_address'];?></td>
		    				<td><?php echo $item['is_active'];?></td>
		    				<td>
		    					<a href="<?php echo $this->baseUrl();?>/admin/phongvien/edit/userid/<?php echo $item['user_id']?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    				<a href="<?php echo $this->baseUrl();?>/admin/phongvien/delete/userid/<?php echo $item['user_id']?>" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    				</td>
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
			<div class="submit_link">
				<a class="alt_btn" href="<?php echo $this->baseUrl('admin/phongvien/insert');?>">Thêm mới</a>
			</div>
		</footer>
	</div>
</article>