<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>Tên</th> 
	    				<th>Năm sinh</th> 
	    				<th>Action</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{?>
				 		<tr>  
		    				<td><?php echo $item->name;?></td> 
		    				<td><?php echo $item->birthday;?></td> 
		    				<td>
		    					<a href="#" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    				<a href="#" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    				</td>
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Add new" class="alt_btn">
			</div>
		</footer>
	</div>
</article>