<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>

<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tên đăng nhập</label>
					<?php echo $this->form->getElement('user_login');?>
					<?php if (isset($_SESSION['result']))
					{
						echo '<br/>';
						echo '<p class="message">';
						echo $_SESSION['result'];
						echo '</p>';
						unset($_SESSION['result']);
					}
					?>
				</fieldset>
				<fieldset>
					<label>Mật khẩu</label>
					<?php echo $this->form->getElement('user_pass');?>
				</fieldset>
				<fieldset>
					<label>Họ tên</label>
					<?php echo $this->form->getElement('user_fullname');?>
				</fieldset>
				<fieldset>
					<label>Email</label>
					<?php echo $this->form->getElement('user_email');?>
				</fieldset>
				<fieldset>
					<label>Địa chỉ</label>
					<?php echo $this->form->getElement('user_address');?>
				</fieldset>
				<fieldset>
					<label>Kích hoạt</label>
					<?php echo $this->form->getElement('is_active');?>
				</fieldset>
				<fieldset>
					<label style="width:300px">Các chuyên mục được phân quyền</label>
					<?php 
					foreach($this->listParent as $parent)
					{
					?>
						<p style="text-transform: uppercase;margin-left: 50px"><?php echo $parent['category_name']; ?></p>
						<?php
							foreach($this->listChild as $child)
							{
								if($child['category_parent_id'] == $parent['category_id'])
								{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $child['category_id']; ?>"/>
										<span><?php echo $child['category_name']; ?></span>
									</div>
										<br/>
									<?php
								}
							}
						?>
					<?php
					}
					?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/phongvien">Hủy bỏ</a>
				<input type="submit" name="submit" value="Thêm" class="alt_btn">
			</div>
		</footer>
	</article>
</form>