<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
<script type="text/javascript">
$(document).ready(function() {
	var check = document.getElementById('is_active-1');
	check.checked = true;
});

function checkall(class_name, obj){
	var items = document.getElementsByClassName(class_name);
	if(obj.checked == true){
		for(i=0;i<items.length;i++)
		items[i].checked = true;
	}
	else{
		for(i=0;i<items.length;i++)
		items[i].checked = false;
	}
}

</script>
<?php if (isset($_SESSION['result']))
					{
						echo '<br/>';
						echo '<p class="message">';
						echo $_SESSION['result'];
						echo '</p>';
						unset($_SESSION['result']);
					}
					?>
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset class="fieldset" style="float:left">
					<label>Tên đăng nhập</label>
					<?php echo $this->form->getElement('user_login');?>
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Mật khẩu</label>
					<?php echo $this->form->getElement('user_pass');?>
				</fieldset >
				<fieldset class="fieldset" style="float:left">
					<label>Họ tên</label>
					<?php echo $this->form->getElement('user_fullname');?>
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Email</label>
					<?php echo $this->form->getElement('user_email');?>
				</fieldset>
				<fieldset class="fieldset" style="float:left">
					<label>Địa chỉ</label>
					<?php echo $this->form->getElement('user_address');?>
				</fieldset>
				<fieldset class="fieldset" style="float:right">
					<label>Kích hoạt</label>
					<div style="margin-left: 84px;margin-top: -29px;">
						<?php echo $this->form->getElement('is_active');?>
					</div>
				</fieldset>
				<fieldset style="margin-left:-1px"  id="checkboxes">
					<label style="width:300px">Các chuyên mục được phân quyền</label>
					<?php 
					foreach($this->listParent as $parent)
					{
					?>
						<input type="checkbox" onclick="checkall('item_<?php echo $parent['category_id']; ?>',this);" name="check_object/>
						<span style="text-transform: uppercase"><?php echo $parent['category_name']; ?></span>
						<?php
							foreach($this->listChild as $child)
							{
								if($child['category_parent_id'] == $parent['category_id'])
								{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $child['category_id']; ?>" class="item_<?php echo $parent['category_id'] ?>"/>
										<span><?php echo $child['category_name']; ?></span>
										</div>
									<?php
								}
							}
						?>
					<?php
					}
					?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/phongvien">Hủy bỏ</a>
				<input type="submit" name="submit" value="Thêm" class="alt_btn">
			</div>
		</footer>
	</article>
</form>
<!--input style="margin-top: 10px;margin-left:60px" type="radio" name="is_active" id="is_active-1" value="1" class="is_active" checked="checked">Có
						<input type="radio" name="is_active" id="is_active-0" value="0" class="is_active">Không