<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ 
										order: "<?php echo $count;?>", 
										category_name: "<?php echo $item['category_name'];?>",   
										category_parent_id: "<?php if($item['category_parent_id']!='0') echo $this->listParent[$count-1];?>",
										is_active: "<?php if ($item['is_active']=='1') echo 'Có'; else echo 'Không';?>",
										sua: "<?php if($this->role == "0") echo '<a href="'.$this->baseUrl().'/admin/chuyenmuc/edit/category_id/'.$item['category_id'].'" title="Edit"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';?>"
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'category_name',
								label: 'Tên chuyên mục',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'category_parent_id',
								label: 'Chuyên mục cha',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'is_active',
								label:'Kích hoạt',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link">
				<?php if($this->role == "0")
				{
					?>
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/chuyenmuc/insert');?>">Thêm mới</a>
					<?php
				}
				echo $this->paginationControl($this->list,
                                    'Sliding',
                                    'tintuc/pagination.phtml');?>
			</div>
		</footer>
	</div>
</article>