<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
$i=0;
?>
<script type="text/javascript" language="javascript">
	function confirmDelete()
	{
		return confirm('Bạn có chắc rằng muốn xóa trưởng ban này?');
	}
</script>

<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr>
						<th align="center">STT</th> 
	    				<th align="center">Tên đăng nhập</th> 
	    				<th align="center">Họ và tên</th>
	    				<th align="center">Email</th>
	    				<th align="center">Kích hoạt</th>
	    				<?php 
	    				if($this->role !="2")
						{
	    				?>
	    					<th align="center">Action</th>
	    				<?php 
						}
	    				?>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{
				 		$i++;
				 		?>
				 		<tr>
				 			<td align="center"><?php echo $i; ?></td>  
		    				<td align="center"><?php echo $item['user_login'];?></td>
		    				<td align="center"><?php echo $item['user_fullname'];?></td> 
		    				<td align="center"><?php echo $item['user_email'];?></td>
		    				<td align="center"><?php if ($item['is_active']=='1') echo 'Có'; else echo 'Không';?></td> 
		    				<?php 
		    					//Khi 1 trưởng ban đăng nhập thì chỉ được sửa thông tin của mình
		    					if($item['user_login'] == $this->user & $this->role == "1")
								{
		    				?>
		    					<td align="center">
		    						<a href="<?php echo $this->baseUrl(); ?>/admin/truongban/edit/userid/<?php echo $item['user_id']; ?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    					</td>
		    				<?php
								}
								
								//Nếu là admin thì full quyền
								if($this->role == "0")
								{
		    				?>
		    					<td align="center">
			    					<a href="<?php echo $this->baseUrl(); ?>/admin/truongban/edit/userid/<?php echo $item['user_id']; ?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
			    					<a href="<?php echo $this->baseUrl(); ?>/admin/truongban/delete/userid/<?php echo $item['user_id']; ?>" onclick="return confirmDelete();" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    					</td>
		    				<?php
								}
		    				?>
		    				
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
			<form>
				<?php
				if($this->role == "0")
				{
				?>
				<div class="submit_link">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/truongban/insert');?>">Thêm mới</a>
				</div>
				<?php 
				}
			       echo $this->paginationControl($this->list, 'Sliding' , 'truongban/pagination.phtml'); 
				?>
		</footer>
	</div>
	</form>
</article>