<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tên đăng nhập</label>
					<?php echo $this->form->getElement('user_login');?>
				</fieldset>
				<fieldset>
					<label>Mật khẩu</label>
					<?php echo $this->form->getElement('user_pass');?>
				</fieldset>
				<fieldset>
					<label>Họ tên</label>
					<?php echo $this->form->getElement('user_fullname');?>
				</fieldset>
				<fieldset>
					<label>Email</label>
					<?php echo $this->form->getElement('user_email');?>
				</fieldset>
				<fieldset>
					<label>Địa chỉ</label>
					<?php echo $this->form->getElement('user_address');?>
				</fieldset>
				<fieldset>
					<label>Kích hoạt</label>
					<?php echo $this->form->getElement('is_active');?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Thêm mới" class="alt_btn">
			</div>
		</footer>
	</article>
</form>