<div style="width:600px; text-align:left;">

<fieldset>
 <br />
 <?php
  	if(isset($_SESSION['login'])&& $_SESSION['usertype']=="user")
	{
		
		print "&nbsp;&nbsp;&nbsp;HI ".$_SESSION['name'];
		print "<br/>";
				
	}
 ?>
 <p style="text-align:justify; margin-left:10px; margin-right:5px">WE STRIVE TO IMPROVE OUR UNIQUE AND POWERFUL FUND PLATFORM SO YOU GET AN ADVANCED TOOL TO WORK WITH. THEREFORE, PLEASE LET US KNOW WHAT ADDITIONAL FEATURES YOU WOULD LIKE TO HAVE TO MAKE YOUR WORK EVEN MORE ENJOYABLE.<br/><br/>OUR AIM IS ALSO TO MAINTAIN THE MOST ACCURATE AND COMPREHENSIVE DATABASE OF HEDGE- AND OFFSHORE FUNDS. IN ORDER TO HELP US ACHIEVE THIS, YOUR FEEDBACK AND SUPPORT IS HIGHLY APPRECIATED.<br/><br/>IF YOU ENCOUNTER A PROBLEM, EITHER CONTACT OUR HELP DESK OR CLICK ON LIVE SUPPORT. REMEMBER, OUR DEDICATED SUPPORT TEAM IS HERE TO ASSIST YOU.<br/><br/>IN THE MEANTIME, GET A BEER OR A GLASS OF WINE AND SETTLE BACK.<br/><br/>CHEERS, MATE!</p></fieldset>
</div>

