<div style="width:600px; text-align:left;">

<fieldset>
 <br />
 <?php
  	if(isset($_SESSION['login'])&& $_SESSION['usertype']=="user")
	{
		
		print "&nbsp;&nbsp;&nbsp;HI ".$_SESSION['name'];
		print "<br/>";
				
	}
 ?>
 <p style="text-align:justify; margin-left:10px; margin-right:5px">WE STRIVE TO IMPROVE OUR UNIQUE AND POWERFUL FUND PLATFORM TO GET YOU AN ADVANCED TOOL TO WORK WITH. THEREFORE, PLEASE LET US KNOW WHAT ADDITIONAL FEATURES YOU WOULD LIKE TO HAVE ADDED, TO MAKE YOUR WORK EVEN MORE ENJOYABLE.<br/><br/>PLEASE HELP US MAINTAIN THE MOST ACCURATE AND COMPREHENSIVE DATABASE OF ALTERNATIVE FUNDS. IN ORDER TO ACHIEVE THIS, YOUR FEEDBACK AND SUPPORT IS HIGHLY APPRECIATED.<br/><br/>IF YOU ENCOUNTER A PROBLEM, EITHER CONTACT OUR HELP DESK OR CLICK ON THE LIVE SUPPORT BUTTON. REMEMBER, OUR DEDICATED SUPPORT TEAM IS HERE TO ASSIST YOU.<br/><br/>IN THE MEANTIME, GET A BEER AND SETTLE BACK.<br/><br/>CHEERS, MATE!</p></fieldset>
</div>

