<div class="element_detail">
	<p style="text-decoration:underline">Kết quả tìm kiếm với từ khóa: <i><?php if (isset($this->key)) echo $this->key;?></i></p>
	<?php 
	if(count($this->list) > 0)
	{
		foreach($this->list as $news)
		{
	?>
		<div style="border-bottom: 1px dotted #CCCCCC" class="subpage_new">
			<div class="img_new">
				<a class="news_avatar" style="color:blue; float:left" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>">
	 			<?php
					if(isset($news['news_avatar']))
					{
						echo $news['news_avatar'];
					} 
					else 
					{
						?>
							<img src="<?php echo $this->baseUrl(); ?>/application/templates/front/images/logo.png" alt="Văn hóa thể thao"/>
						<?php
					}
	 			?>
	 			</a>
	 		</div>
	 		<div class="text_new" style="margin-top:0px">
	  			<a class="a-title" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title']; ?></a></h3>
	  			<p class="text">
	  				<?php
	  				 	$str = $news['news_summary']; 
						
						$preg1 = preg_match_all('#<img.*/>#',$str,$match);
						if($preg1 > 0)
						{
							$str = str_replace($match[0][0],"", $str);
						}
						
						$preg2 = preg_match('#<br>.*</a>#',$str,$match);
						if($preg2 > 0)
						{
							$str = str_replace($match[0],"", $str);
						}
						$str = strip_tags($str);
						echo $str;						
	  				?>
	  			</p>
	 		</div>
	 		<br style="clear:both">
	 	</div>
 	<?php
		}
	}
	else 
	{
	?>
		<h3 style="margin:10px;color:red"><i>Không tìm thấy kết quả</i></h3>
	<?php
	}
 	?>
</div>
<div style="margin-top:40px;float:right">
<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
</div>