<div style="margin-top:10px">
	<?php 
	if(count($this->list) > 0)
	{
		foreach($this->list as $news)
		{
	?>
		<div style="margin-top:10px">
				<a class="news_avatar" style="color:blue; float:left" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>">
	 			<?php
					if(isset($news['news_avatar']))
					{
						echo $news['news_avatar'];
					} 
					else 
					{
						?>
							<img src="<?php echo $this->baseUrl(); ?>/application/templates/front/images/logo.png" alt="Văn hóa thể thao"/>
						<?php
					}
	 			?>
	 			</a>
	 		
	 		<div style="float:right">
	  			<h3 style="color:blue;margin-left:145px;margin-top:-92px"><a style="color:#07506b" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title']; ?></a></h3>
	  			<div style="margin-left:145px">
	  				<?php
	  				 	$str = $news['news_summary']; 
						
						$preg1 = preg_match_all('#<img.*/>#',$str,$match);
						if($preg1 > 0)
						{
							$str = str_replace($match[0][0],"", $str);
						}
						
						$preg2 = preg_match('#<br>.*</a>#',$str,$match);
						if($preg2 > 0)
						{
							$str = str_replace($match[0],"", $str);
						}
						$str = strip_tags($str);
						echo $str;						
	  				?>
	  			</div>
	  			
	  			<a style="float:right; color:#07506b" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html">Xem tiếp</a>
	 		</div>
	 		<br style="clear:both">
	 	</div>
	 	
 	<?php
		}
	}
	else 
	{
	?>
		<h3 style="margin:10px;color:red"><i>Không tìm thấy kết quả</i></h3>
	<?php
	}
 	?>
</div>
<div style="margin-top:40px;float:right">
<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
</div>