<?php function cutString($str,$limit)
{
	if (strlen($str)>$limit)
	{
		while ($str[$limit]!=' ' && $limit<strlen($str)-1)
			$limit++;
	}
	else $limit=strlen($str);
	if ($limit<strlen($str))
		return substr($str, 0, $limit).'...';
	else return substr($str, 0, $limit);
}?>	
<div class="subpage_wapper_left">
	<div class="subpage_wapper_left_top_video">
            	video clips
            </div>
            <div class="subpage_new" style="margin:10px 5px 5px 2px">
            	<div id="videp_left">
                	<form class="searchform" action="<?php echo $this->baseUrl();?>/timkiem/searchvideo" method="post">
                        <input name="search-text" class="t" onfocus="if (this.value == 'Tìm kiếm …') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Tìm kiếm …';}" type="text" value="Tìm kiếm …">
                        <input class="searchsubmit" type="submit" value="" style="cursor:pointer">
                    </form>
                    <ul id="ul_video_left">
                    	<?php 
							foreach($this->menuvideo as $menuvideo)
							{
						?>
                    	<li><a href="<?php echo $this->baseUrl(); ?>/video/danh-sach/<?php echo $menuvideo['category_id']; ?>-1-<?php if(isset($menuvideo['video_alias'])) echo $menuvideo['video_alias']; ?>.html"><?php echo $menuvideo['category_name']; ?></a></li>
                    	<?php
							}
					 	?>
                    </ul>
                </div>
                	
    <!---------Tìm kiếm------->
    <div id="video_right" style="width: 486px" >
		<?php 
	if($this->list != NULL)
	{
	?>
                	<ul>
                		<?php 
							foreach($this->list as $video)
							{
						?>
							<li><a href="<?php echo $this->baseUrl(); ?>/video/<?php echo $video['video_id']; ?>-<?php if(isset($video['video_alias'])) echo $video['video_alias']; ?>.html">
								<img src="http://img.youtube.com/vi/<?php echo $video['video_link']; ?>/1.jpg" style="box-shadow:0 2px 5px 0 #505050"/>
	                            <p><?php echo cutString($video['video_title'],20); ?></p>
	                        </a></li>
						<?php
							}
					 	?>
                    </ul>
                    <div class="page_video" style="clear:both; padding-top:100px; margin-bottom:15px">
                    	
                    	<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
                    </div>
		 	<?php
			}
			else 
			{
			?>
				<h3 style="margin:10px;color:red"><i>Không tìm thấy kết quả</i></h3>
			<?php
			}
		?>
		<div class="clear"> </div>
		</div>
			<!---------End Tìm kiếm------->
            </div>
</div>          