<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script type="text/javascript">
	$(function() {
		setUpFCK('image_link',200,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
	});
</script>
<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>

<script type="text/javascript">
//<!-----------Check all----->
	function checkall(class_name, obj){
		var items = document.getElementsByClassName(class_name);
		if(obj.checked == true){
			for(i=0;i<items.length;i++)
			items[i].checked = true;
		}
		else{
			for(i=0;i<items.length;i++)
			items[i].checked = false;
		}
	}
//<!-------End Check all----->
</script>

					<?php if (isset($_SESSION['result']))
					{
						echo '<p class="message">';
						echo $_SESSION['result'];
						echo '</p>';
						unset($_SESSION['result']);
					}
					?>
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset class="fieldset" style="float:left">
					<label>Tên ảnh</label>
					<?php echo $this->form->getElement('image_name');?>
				</fieldset> 
				<fieldset class="fieldset" style="float:right">
					<label>Kích hoạt</label>
					<div style="margin-left: 82px;margin-top: -26px;">
						<?php echo $this->form->getElement('is_active');?>
					</div>
				</fieldset>
				<fieldset style="width:100%">
					<label>Hình ảnh</label>
					<?php echo $this->form->getElement('image_link');?>
				</fieldset>
				<fieldset style="margin-left:-1px" id="checkboxes">
					<label style="width:300px">Danh sách chuyên mục</label>
						<div style="margin-left:60px;margin-bottom:10px">
							<input type="checkbox" onclick="checkall('item',this);" name="check_object"/>
							<span style="text-transform: uppercase">Chọn tất cả</span>
						</div>
						<?php
							foreach($this->listAllImageCategory as $allCategory)
							{
								$check = 0 ;
								foreach ($this->listCategory as $category)
								{
									
									if($allCategory['category_id'] == $category)
									{
										$check = 1;
										break;
									}
								}
								if($check == 1)
								{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $allCategory['category_id']; ?>" class="item" checked="checked"/>
										
										<span><?php echo $allCategory['category_name']; ?></span>
									</div>
									<?php
								}
								else{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $allCategory['category_id']; ?>" class="item"/>
										<span><?php echo $allCategory['category_name']; ?></span>
									</div>
									<?php
								}
							}
						?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/truongban">Hủy bỏ</a>
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>