<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>

<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset  class="fieldset" style="float:left">
					<label>Liên kết </label>
					<?php echo $this->form->getElement('link');?>
				</fieldset>
				<fieldset  class="fieldset" style="float:right">
					<label>Tiêu đề </label>
					<?php echo $this->form->getElement('title');?>
				</fieldset>
				<fieldset class="fieldset1" style="float:left">
					<label>Mô tả</label>
					<?php echo $this->form->getElement('description');?>
				</fieldset>
				<!--fieldset>
					<label>Chuyên mục</label>
					<?php echo $this->form->getElement('category_id');?>
				</fieldset-->
				<?php 
				if($this->role == "0")
				{
				?>
					<fieldset class="fieldset" style="float:right">
						<label>Kích hoạt</label>
						<div style="margin-top: 26px;margin-left:82px">
							<?php echo $this->form->getElement('is_active');?>
						</div>
					</fieldset>
				<?php 
				}
				?>
				<fieldset class="fieldset" id="checkboxes">
					<label style="width:300px">Danh sách chuyên mục</label>
						<div style="margin-left:60px;margin-bottom:10px">
							<input type="checkbox" onclick="checkall('item',this);" name="check_object"/>
							<span style="text-transform: uppercase">Chọn tất cả</span>
						</div>
						<?php
							foreach($this->listCategory as $allCategory)
							{
								$check = 0 ;
								foreach($this->listCategoryId as $category)
								{
									if($allCategory['category_id'] == $category)
									{
										$check = 1;break;
									}
								}
								if($check == 1)
								{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $allCategory['category_id']; ?>" class="item" checked="checked"/>
										<span><?php echo $allCategory['category_name']; ?></span>
									</div>
									<?php
								}
								else{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $allCategory['category_id']; ?>" class="item"/>
										<span><?php echo $allCategory['category_name']; ?></span>
									</div>
									<?php
								}
							}
						?>
			</fieldset>
				<!--fieldset>
					<label>Đặt làm mặc định</label>
					<?php echo $this->form->getElement('is_default');?>
				</fieldset-->
			</div>
		</div>
		<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/uploadvideo">Hủy bỏ</a>
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>