<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/uploadvideo/edit/video_link/<?php echo $this->video['video_link']; ?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tiêu đề </label>
					<input type="text" name="video_title" value="<?php echo $this->video['video_title'] ?>"/>
				</fieldset>
				<fieldset>
					<label>Mô tả</label>
					<input type="text" name="video_description" value="<?php echo $this->video['video_description']?>"
				</fieldset>
				<fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>