<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tiêu đề </label>
					<?php echo $this->form->getElement('title');?>
				</fieldset>
				<fieldset>
					<label>Mô tả</label>
					<?php echo $this->form->getElement('description');?>
				</fieldset>
				<fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Cập nhật" class="alt_btn">
			</div>
		</footer>
	</article>
</form>