<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
				function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa video này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/uploadvideo/del/video_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header>
		<h3><?php echo $this->title;?></h3>
		<!--a class="alt_btn" style="float:right;margin-top: -3%;margin-right: 3px;" href="<?php echo $this->baseUrl('admin/uploadvideo/refresh');?>">Làm mới</a-->
	</header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ 	order: "<?php echo $count;?>", 
										video_title: "<?php echo $item['video_title'];?>",   
										video_description: "<?php echo $item['video_description'];?>",
										video_full_link: '<a href="<?php echo $item['video_full_link'];?>"><?php echo $item['video_full_link'];?></a>',
										sua: '<?php
											if($this->role == "0" |(($this->role=="1" | $this->role=="2") & $this->user_login==$item['user_upload']))
												echo '<a href="'.$this->baseUrl().'/admin/uploadvideo/edit/video_id/'.$item['video_id'].'" title="Edit"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
										?>',
										xoa : 
										'<?php
											if($this->role == "0" |(($this->role=="1" | $this->role=="2") & $this->user_login==$item['user_upload']))
												echo '<a class="del_button" onclick="confirmDel('.$item['video_id'].')" title="Del"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
										?>'
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: "order",
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'video_title',
								label: 'Tiêu đề',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'video_description',
								label: 'Mô tả',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'video_full_link',
								label:'Liên kết',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							},
							{
								key: 'xoa',
								label:'<center>Xóa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link">
					<?php
						if($this->role=="0")
						{
					?>				
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/youtube');?>">Quản lý tài khoản Youtube</a>
					<?php
						}
					?>
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo/insert');?>">Thêm mới video</a>
			
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo/upload');?>">Upload video</a>
				<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
			</div>
		</footer>
	</div>
</article>
