<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
				function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa video này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/uploadvideo/del/video_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header>
		<h3><?php echo $this->title;?></h3>
	</header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
		$(document).ready(function() {
			$('#listnews').dataTable({
				"sPaginationType": "full_numbers",
				"iDisplayLength": 25
			});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Thứ tự</th>
				<th>Tiêu đề</th>
				<th>Mô tả</th>
				<th>Liên kết</th>
				<th>Kích hoạt</th>
				<th style="background:transparent">Sửa</th>
				<th style="background:transparent">Xóa</th>
			</thead>
			<tbody>
				<?php 
				$count=1;
				foreach ($this->list as $item)
				{?>
					<tr>
						<td><?php echo $count;?></td>
						<td><?php echo $item['video_title'];?></td>
						<td><?php echo $item['video_description'];?></td>
						<td><a href="<?php echo $item['video_full_link'];?>"><?php echo $item['video_full_link'];?></a></td>
						<td><?php if($item['is_active'] == '1') echo 'Có'; else echo 'Không';?></td>
						
						<td><?php if($this->role == "0" |(($this->role=="1" | $this->role=="2") & $this->user_login==$item['user_upload']))
												echo '<a href="'.$this->baseUrl().'/admin/uploadvideo/edit/video_id/'.$item['video_id'].'" title="Sửa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
										?></td>
						<td><?php
											if($this->role == "0" |(($this->role=="1" | $this->role=="2") & $this->user_login==$item['user_upload']))
												echo '<a class="del_button" onclick="confirmDel('.$item['video_id'].')" title="Xóa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
										?></td>
					</tr>
				<?php $count++;}?>
			</tbody>
		</table>
		
		<footer>
			<div class="submit_link" style="float:right">
					<?php
						if($this->role=="0")
						{
					?>				
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/youtube');?>">Quản lý tài khoản Youtube</a>
					<?php
						}
					?>
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo/insert');?>">Thêm mới video</a>
			
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo/upload');?>">Upload video</a>
			</div>
			<div class="submit_link" style="float:left; font-weight: bold;">
				</div>
		</footer>
	</div>
</article>
