<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script type="text/javascript">
	$(function() {
		setUpFCK('description',200,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
	});
</script>
<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/uploadvideo/insert" enctype="multipart/form-data">
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<fieldset>
				<label>Liên kết</label>
				<?php echo $this->form->getElement('link');?>
			</fieldset>
			<fieldset>
				<label>Tiêu đề</label>
				<?php echo $this->form->getElement('title');?>
			</fieldset>
			<fieldset>
				<label>Mô tả</label>
				<?php echo $this->form->getElement('description');?>
			</fieldset>
			<fieldset>
				<label>Chuyên mục</label>
				<?php echo $this->form->getElement('category_id');?>
			</fieldset>
			<?php 
				if($this->role == "0")
				{
			?>
				<fieldset>
					<label>Kích hoạt</label>
					<?php echo $this->form->getElement('is_active');?>
				</fieldset>
			<?php 
				}
			?>
		</div>
	</div>
	<footer>
			<div class="submit_link">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/uploadvideo">Hủy bỏ</a>
				<input type="submit" name="submit" value="Thêm mới" class="alt_btn">
			</div>
		</footer>
</article>
</form>