<script type="text/javascript">
$(document).ready(function() {
	var check = document.getElementById('is_active-1');
	check.checked = true;
});
function checkall(class_name, obj){
		var items = document.getElementsByClassName(class_name);
		if(obj.checked == true){
			for(i=0;i<items.length;i++)
			items[i].checked = true;
		}
		else{
			for(i=0;i<items.length;i++)
			items[i].checked = false;
		}
	}
</script>
<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/uploadvideo/insert" enctype="multipart/form-data">
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<fieldset class="fieldset">
				<label>Liên kết</label>
				<?php echo $this->form->getElement('link');?>
			</fieldset>
			<fieldset class="fieldset">
				<label>Tiêu đề</label>
				<?php echo $this->form->getElement('title');?>
			</fieldset>
			<fieldset>
				<label>Mô tả</label>
				<?php echo $this->form->getElement('description');?>
			</fieldset>
			<!--fieldset class="fieldset">
				<label>Chuyên mục</label>
				<?php echo $this->form->getElement('category_id');?>
			</fieldset-->
			<?php 
				if($this->role == "0")
				{
			?>
				<fieldset class="fieldset" style="float:right;margin-top:-298px;padding-bottom: 47px;">
					<label>Kích hoạt</label>
					<div style="margin-left: 82px;">
						<?php echo $this->form->getElement('is_active');?>
					</div>
				</fieldset>
			<?php 
				}
			?>
			<fieldset id="checkboxes">
					<label style="width:300px">Danh sách chuyên mục</label>
						<div style="margin-left:60px;margin-bottom:10px">
							<input type="checkbox" onclick="checkall('item',this);" name="check_object"/>
							<span style="text-transform: uppercase">Chọn tất cả</span>
						</div>
						<?php
							foreach($this->listCategory as $category)
							{
									?>
									<div style="margin-left:100px">
										<input type="checkbox" name="checkbox[]" value="<?php echo $category['category_id']; ?>" class="item"/>
										<span><?php echo $category['category_name']; ?></span>
									</div>
									<?php
							}
						?>
			</fieldset>
			<!--fieldset class="fieldset">
					<label>Đặt làm mặc định</label>
					<?php echo $this->form->getElement('is_default');?>
			</fieldset-->
		</div>
	</div>
	<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/uploadvideo">Hủy bỏ</a>
				<input type="submit" name="submit" value="Thêm mới" class="alt_btn">
			</div>
		</footer>
</article>
</form>