<style>
	.errors{list-style-type:none; color: red; padding:10px}
	.uploading_inline{display:inline}
</style>
<script type="text/javascript">
	function showLoading()
	{
		var uploading = document.getElementById('uploading');
		uploading.style.display = 'block';
		$('.uploading').addClass('uploading_inline');
		$('.file').addClass('uploading_inline');
	}
</script>
<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/uploadvideo/upload" enctype="multipart/form-data" onsubmit="showLoading();">
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<fieldset>
				<label>Chọn video</label>
				<input class="file" id="file" type="file" name="file"/><img class="uploading" id="uploading" style="display:none" src="<?php echo $this->baseUrl() ?>/application/templates/admin/images/uploading.gif"/>
			</fieldset>
			<fieldset>
				<label>Tiêu đề</label>
				<?php echo $this->form->getElement('title');?>
			</fieldset>
			<fieldset>
				<label>Mô tả</label>
				<?php echo $this->form->getElement('description');?>
			</fieldset>
		</div>
	</div>
	<footer>
			<div class="submit_link" style="float:right">
				<a class="alt_btn" style="margin-left:10px" href="<?php echo $this->baseUrl(); ?>/admin/uploadvideo">Hủy bỏ</a>
				<input type="submit" name="submit" value="Upload" class="alt_btn">
			</div>
		</footer>
</article>
</form>