<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
				function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa tài khoản youtube này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/youtube/delete/youtube_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header>
		<h3><?php echo $this->title;?></h3>
		<!--a class="alt_btn" style="float:right;margin-top: -3%;margin-right: 3px;" href="<?php echo $this->baseUrl('admin/uploadvideo/refresh');?>">Làm mới</a-->
	</header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ 	order: "<?php echo $count;?>", 
										youtube_username: "<?php echo $item['youtube_username'];?>",   
										youtube_gallery: "<?php echo $item['youtube_gallery'];?>",
										is_selected: '<?php if($item['is_selected'] == "1") echo 'Có'; else echo 'Không';?>',
										sua: 
											'<?php
												echo '<a href="'.$this->baseUrl().'/admin/youtube/edit/id/'.$item['youtube_id'].'" title="Sửa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
											?>',
										xoa : 
											'<?php
												echo '<a class="del_button" onclick="confirmDel('.$item['youtube_id'].')" title="Xóa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
											?>'
									},
								<?php $count++;}?>
							];
				
				var count = 1;
				
				var table = new Y.DataTable({
					columns: [{
								key: "order",
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'youtube_username',
								label: 'Tên tài khoản',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'youtube_gallery',
								label: 'Tên album',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'is_selected',
								label:'Kích hoạt',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							},
							{
								key: 'xoa',
								label:'<center>Xóa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<form>
				<div class="submit_link">
					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/youtube/insert');?>">Thêm tài khoản mới</a>

					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo/insert');?>">Thêm mới video</a>

					<a class="alt_btn" style="margin-left: 10px;" href="<?php echo $this->baseUrl('admin/uploadvideo');?>">Quản lý tải lên video</a>
				</div>
				<?php 
			       echo $this->paginationControl($this->list, 'Sliding' , 'tintuc/pagination.phtml'); 
				?>
		</footer>
	</div>
</article>