<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa danh mục này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/getnewssetting/del/campaign_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ 
										order: "<?php echo $count;?>", 
										name: "<?php echo $item['category_name'];?>",   
										edit: "<?php echo $item['category_id']?>"
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'name',
								label: 'Tên danh mục',
								sortable:true,
								formatter: '<span>{value}</span>',//<a style="text-decoration:underline" href="<?php echo $this->baseUrl();?>/admin/getnewssetting/showlistrss/campaign_name/{value}">{value}</a>,
								allowHTML: true 
							},
							{
								key: 'edit',
								label:'<center>Chi tiết</center>',
								formatter: '<center><a href="<?php echo $this->baseUrl();?>/admin/getnewssetting/showlistrss/campaign_id/{value}" title="Chi tiết"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a></center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link" style="float:right">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/getnewssetting/insert');?>">Thêm mới</a>
			</div>
			<div class="submit_link" style="float:left; font-weight: bold;">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>