<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa rss này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/getnewssetting/delrss/rss_id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=1;
								foreach ($this->list as $item)
								{?>
									{ 
										order: "<?php echo $count;?>", 
										link: "<?php echo $item['link'];?>",
										campaign: "<?php echo $this->listCampaign[$count-1];?>",   
										edit: "<?php echo $item['id']?>",
										delete: "<?php echo $item['id']?>"
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'link',
								label: 'Link',
								sortable:true,
								formatter: '<a href="{value}">{value}</a>',
								allowHTML: true 
							},
							{
								key: 'campaign',
								label:'<center>Danh mục</center>',
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'edit',
								label:'<center>Sửa</center>',
								formatter: '<center><a href="<?php echo $this->baseUrl();?>/admin/getnewssetting/editrss/rss_id/{value}" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a></center>',
								allowHTML: true
							},
							{
								key: 'delete',
								label:'<center>Xóa</center>',
								formatter: '<center><a class="del_button" onclick="confirmDel({value})" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a></center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link" style="float:right">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/getnewssetting/insertrss');?>">Thêm mới</a>
			</div>
			<div class="submit_link" style="float:left; font-weight: bold;">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>