<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	
		<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/jquery.ui.all.css">
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.datepicker.js"></script>
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/demos.css">
		
		<!--Thêm ảnh-->
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
		<script language="javascript" type="text/javascript" src="/unc/application/templates/admin/js/customs.js"></script>

		<script>
		$(function() {
			$( ".datepicker" ).datepicker();
			// Up ảnh
			setUpFCK('ads_banner',400,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
		});
		</script>

	</head>
	
	<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/quangcao/add">
		<div class="module_content">
			
			<fieldset style="width:50%">
				<label>Nội dung</label>
				<!--<input style="width:93%" type="text" name="ads_banner"/>-->
				<?php echo $this->form->getElement('ads_banner');?>
				
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Vị trí</label>
				<!--<input style="width:93%" type="text" name="ads_position"/>-->
				<?php echo $this->form->getElement('ads_position');?>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Tên</label>
				<!--<input style="width:93%" type="text" name="ads_name"/>-->
				<?php echo $this->form->getElement('ads_name');?>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Đường dẫn</label>
				<!--<input style="width:93%" type="text" name="ads_link"/>-->
				<?php echo $this->form->getElement('ads_link');?>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Ngày bắt đầu</label>
				<input style="width:93%" type="text" name="ads_start_date" class="datepicker"/>				
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Ngày hết hạn</label>
				<input style="width:93%" type="text" name="ads_end_date" class="datepicker"/>
			</fieldset><div class="clear"></div>
				
			<fieldset style="width:50%">
				<label>chuyên mục : </label>
				<select name="category_id">
					<option value="0"></option>
					<?php
						foreach($this->listdm as $item)
						{
							?>
								<option value="<?php echo $item['category_id']; ?>"><?php echo $item['category_name']; ?></option>
							<?php 
						}
					?>
				</select>
			</fieldset><div class="clear"></div>
		</div>
			<footer>
					<div class="submit_link" style="float:right ">
						<input type="submit" name="submit" value="Thêm quảng cáo" class="alt_btn">
					</div>
					<div class="submit_link" style="float:right">
						<input type="reset" value="Làm lại" class="alt_btn">
					</div>
				
			</footer>
	</form>
</article>