<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/jquery.ui.all.css">
		
		<!-- Lấy lịch -->
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.datepicker.js"></script>
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/demos.css">
		<!--Up ảnh-->
		<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
		<script language="javascript" type="text/javascript" src="/unc/application/templates/admin/js/customs.js"></script>

		<script>
		$(function() {
			$( ".datepicker" ).datepicker();
		// Up ảnh
			setUpFCK('ads_banner',400,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
		});
		</script>
		<!--/End lấy lịch -->
				
	</head>

	<form method="post" action="<?php echo $this->baseUrl(); ?>/admin/quangcao/edit?id=<?php echo $this->query['ads_id']; ?>">
		<div class="module_content">
			
			<fieldset style="width:50%">
				<label>Nội dung</label>
				<textarea style="width:93%" type="text" id="ads_banner" name="ads_banner"><?php echo $this->query['ads_banner']; ?></textarea>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Vị trí</label>
				<?php echo $this->form->getElement('ads_position');?>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Tên</label>
				<input style="width:93%" type="text" name="ads_name" value="<?php echo $this->query['ads_name']; ?>"/>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Đường dẫn</label>
				<input style="width:93%" type="text" name="ads_link" value="<?php echo $this->query['ads_link']; ?>"/>
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%" class="demo">
				<label>Ngày bắt đầu</label>					
				<input style="width:93%" type="text" class="datepicker" name="ads_start_date" value="<?php echo $this->query['ads_start_date']; ?>">
			</fieldset><div class="clear"></div>
			
			<fieldset style="width:50%">
				<label>Ngày hết hạn</label>
				<input style="width:93%" type="text" class="datepicker" name="ads_end_date" value="<?php echo $this->query['ads_end_date']; ?>">
			</fieldset><div class="clear"></div>
		</div>
			<footer>
					<div class="submit_link" style="float:right">
						<input type="submit" name="submit" value="Update" class="alt_btn">
					</div>
					<div class="submit_link" style="float:right">
						<input type="reset" value="Làm lại" class="alt_btn">
					</div>
			</footer>
	</form>
</article>