<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa mục này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/quangcao/del/id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
		$(document).ready(function() {
			$('#listnews').dataTable({
				"sPaginationType": "full_numbers",
				"iDisplayLength": 25
			});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th>Thứ tự</th>
				<th>Nội dung</th>
				<th>Vị trí</th>
				<th>Tên</th>
				<th>Ngày bắt đầu</th>
				<th>Chuyên mục</th>
				<th style="background:transparent">Sửa</th>
				<th style="background:transparent">Xóa</th>
			</thead>
			<tbody>
				<?php 
				$count=1;
				foreach ($this->list as $item)
				{?>
					<tr>
						<td><?php echo $count;?></td>
						<td><?php echo $item['ads_banner'];?></td>
						<td><?php 
										 if ($item['ads_position']=='1') {
											 echo "Trên";
										 } else if($item['ads_position']=='2') {
											 echo "Giữa";
										 } else if($item['ads_position']=='3') {
											 echo "Trái";
										 } else if($item['ads_position']=='4') {
											 echo "Phải";
										 } else {
											 echo "Nội dung";
										 }?></td>
										 
						<td><?php echo $item['ads_name'];?></td>
						<td><?php echo $item['ads_start_date'];?></td>
						<td><?php echo $item['category_name'];?></td>
						<td><?php if($this->role =="0")
									echo '<a href="'.$this->baseUrl().'/admin/quangcao/edit/id/'.$item['ads_id'].'" title="Sửa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
											?></td>
						<td><?php if($this->role =="0")
									echo '<a class="del_button" onclick="confirmDel('.$item['ads_id'].')" title="Xóa"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
											?></td>
					</tr>
				<?php $count++;}?>
			</tbody>
		</table>
		<footer>
				<div class="submit_link" style="float:right">
				<?php
				if($this->role=="0")
				{
				?>
					<a class="alt_btn" href="<?php echo $this->baseUrl(); ?>/admin/quangcao/add">Thêm mới</a>
				<?php } ?>
				</div>
				
				<div class="submit_link" style="float:left; font-weight: bold;">
				</div>
		</footer>
	</div>
</article>