<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>ID</th> 
	    				<th>Biểu ngữ</th> 
	    				<th>Vị trí</th>
	    				<th>Tên</th>
	    				<th>Đường dẫn</th>
	    				<th>Ngày bắt đầu</th>
	    				<th>Ngày hết hạn</th>
	    				<th>ID_DM</th>
	    				<th>Actions</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php foreach ($this->list as $item)
				 	{?>
				 		<tr>  
		    				<td><?php echo $item['ads_id'];?></td> 
		    				<td><?php echo $item['ads_banner'];?></td>
		    				<td><?php echo $item['ads_position'];?></td>
		    				<td><?php echo $item['ads_name'];?></td> 
		    				<td><?php echo $item['ads_link'];?></td> 
		    				<td><?php echo $item['ads_start_date'];?></td> 
		    				<td><?php echo $item['ads_end_date'];?></td> 
		    				<td><?php echo $item['category_id'];?></td>
		    				<td>
		    				<a href="<?php echo $this->baseUrl(); ?>/admin/quangcao/edit?id=<?php echo $item['ads_id']; ?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    				<a href="<?php echo $this->baseUrl(); ?>/admin/quangcao/del?id=<?php echo $item['ads_id']; ?>" title="Delete"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>
		    				
		    				</td>
						</tr>
				 	<?php }?>
				</tbody>
			</table>
		</div>
		<footer>
				<div class="submit_link">
					<a class="alt_btn" href="<?php echo $this->baseUrl(); ?>/admin/quangcao/add">Thêm mới</a>
				</div>
		</footer>
	</div>
</article>