<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa mục này ?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/quangcao/del/id/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
	.yui3-datatable-table{width:100% !important}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>
<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
							<?php 
								$count=1;
								foreach ($this->list as $item)
								{
									?>
									{ 
										order: "<?php echo $count;?>", 
										ads_banner: '<?php echo $item['ads_banner'];?>',	
										ads_position: "<?php echo $item['ads_position'];?>",
										ads_name: "<?php echo $item['ads_name'];?>",
										ads_link: "<?php echo $item['ads_link'];?>",
										ads_start_date: "<?php echo $item['ads_start_date'];?>",
										ads_end_date: "<?php echo $item['ads_end_date'];?>",
										category_id: "<?php echo $item['category_id'];?>",
										sua: 
											'<?php 
											//echo "string";
												if($this->role =="0")
													echo '<a href="'.$this->baseUrl().'/admin/quangcao/edit/id/'.$item['ads_id'].'" title="Edit"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_edit.png"></a>';
											?>',
										xoa: 
											'<?php
												if($this->role =="0")
													echo '<a class="del_button" onclick="confirmDel('.$item['ads_id'].')" title="Del"><img src="'.$this->baseUrl().'/application/templates/admin/images/icn_trash.png"></a>';
											?>'
									},
							<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'order',
								label: 'Số thứ tự',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'ads_banner',
								label: 'Biểu ngữ',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'ads_position',
								label: 'Vị trí',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'ads_name',
								label:'Tên',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'ads_link',
								label:'Đường dẫn',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'ads_start_date',
								label:'Ngày bắt đầu',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'Ngày kết thúc',
								label:'Tên',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'category_id',
								label:'ID chuyên mục',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'sua',
								label:'<center>Sửa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							},
							{
								key: 'xoa',
								label:'<center>Xóa</center>',
								formatter: '<center>{value}</center>',
								allowHTML: true
							}],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		<footer>
				<div class="submit_link">
				<?php
				if($this->role=="0")
				{
				?>
					<a class="alt_btn" href="<?php echo $this->baseUrl(); ?>/admin/quangcao/add">Thêm mới</a>
				<?php } ?>
				</div>
				
				<div class="submit_link">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>