<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Mon, 07 May 2012 07:09:52 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    2 => 
    array (
      'categoryid' => '2',
      'catparentid' => '0',
      'catname' => 'Shop iPhone',
      'catdepth' => '0',
    ),
    3 => 
    array (
      'categoryid' => '3',
      'catparentid' => '0',
      'catname' => 'Shop iPod',
      'catdepth' => '0',
    ),
    1 => 
    array (
      'categoryid' => '1',
      'catparentid' => '0',
      'catname' => 'Shop Mac',
      'catdepth' => '0',
    ),
  ),
);
