<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa tin tức này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/tintuc/delete/newsid/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>

<article class="module width_full" onload="abc()">
	<header><h3 style="width: 35%"><?php echo $this->title;?></h3>             
		<div id="subpage_search" style="padding-top:5px" >
            	<form class="search-form" action="<?php echo $this->baseUrl("admin/tintuc/timkiem");?>" method="post">
					<!-- input name="search-text" class="t" onfocus="if (this.value == 'Tìm kiếm …') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Tìm kiếm …';}" type="text" value="Tìm kiếm …"/>
					<input class="searchsubmit" type="submit" value="Tìm kiếm" style="cursor:pointer; height: 21px; padding-bottom:1px"/ -->
					<select id="viewtype" onchange="return selectViewChange();" style="float: right">
						<option value="1">Xem tất cả</option>
						<?php if ($_SESSION['role_id']=="2")
						{?>
							<option value="2">Tin tự động đã xác nhận</option>
							<option value="3">Tin tự động đã review, chưa xác nhận</option>
							<option value="4">Tin viết đã xác nhận</option>
							<option value="5">Tin viết đã review, chưa xác nhận</option>
							<option value="6">Tin viết chưa submit</option>
							<option value="7">Tin tự động chưa review</option>
						<?php }
						elseif ($_SESSION['role_id']=="1")
						{?>
							<option value="2">Tin theo chuyên mục phụ trách</option>
							<option value="3">Tin viết đã review, chưa duyệt</option>
							<option value="4">Tin tự động đã review, chưa duyệt</option>
							<option value="5">Tin viết đã xác nhận</option>
							<option value="6">Tin tự động đã xác nhận</option>
						<?php }?>
						<?php 
						$incres=0;
						if ($_SESSION['role_id']=="2") $increase=7;
						elseif ($_SESSION['role_id']=="1") $increase=6;
						elseif ($_SESSION['role_id']=="0") $increase=1;
						
						if ($_SESSION['role_id']=="2" || $_SESSION['role_id']=="1")
						foreach($this->listCategories as $cat)
						{?>
							<option value="<?php echo $increase+$cat['category_id'];?>"><?php echo $cat['category_name']?></option>	
						<?php }?>
					</select>
				</form>
				<script>
				function selectViewChange() {
					var go=$("#viewtype").val();
				  window.location = '<?php echo $this->baseUrl("admin/tintuc/index/viewtype/");?>'+go;
				}
				</script>				
            </div>
    </header>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table_jui.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_table.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/demo_page.css"/>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/css/jquery.dataTables_themeroller.css"/>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/application/templates/admin/datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
	$(document).ready(function() {
		$('#listnews').dataTable({
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
			"bLengthChange": false,
			"bProcessing": true,
	        "bServerSide": true,
	        "sAjaxSource": "<?php echo $this->baseUrl();?>/admin/tintuc/loaddata/viewtype/1"
		});
		});
	</script>
	<style type="text/css">
		.paging_full_numbers{float:none !important; width:auto !important; margin-top:15px !important}
	</style>
	<div class="tab_container">
		<table id="listnews">
			<thead>
				<th style="width:106px">Tiêu đề</th>
				<th style="width:121px">Ảnh đại diện</th>
				<th style="width:342px">Tóm tắt</th>
				<th style="width:76px">Tác giả</th>
				<th style="width:89px">Ngày sửa</th>
				<th style="width:91px">Trạng thái</th>
				<th  style="width:73px">Tin hot</th>
				<th style="background:transparent">Sửa</th>
				<th style="background:transparent">Xóa</th>
			</thead>
			<tbody>
				<tr>
					<td colspan="5" class="dataTables_empty">Loading data from server</td>
				</tr>
			</tbody>
		</table>
		<footer>
				<div class="submit_link" style="float:right">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/tintuc/insert');?>">Thêm mới</a>
				</div>
				
				<div class="submit_link" style="float:left; font-weight: bold;">
					<!-- ?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');? -->
					<div id="pagContainerBar" style="margin-top: 4px; margin-left:100px"></div>
				</div>
		</footer>
	</div>
	<script type="text/javascript">
		var viewtype="<?php if (isset($_SESSION['current_view_type'])) echo $_SESSION['current_view_type']; else echo '1';?>";
		$("#viewtype").val(viewtype);
	</script>
</article>