<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa tin tức này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/tintuc/delete/newsid/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
		

		/*function abc()
		{
			var listDel=document.getElementsByClassName('del_button');
			for (var i=0;i<listDel.length;i++)
			{
				var onclick=listDel[i].getAttribute("onclick");
				if (onclick=='confirmDel( )')
				{
					listDel[i].setAttribute("style","display:none");
				}
			}
		}*/
</script>
<style>
	.del_button{cursor:pointer}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>

<article class="module width_full" onload="abc()">
	<header><h3 style="width: 35%"><?php echo $this->title;?></h3>             
		<div id="subpage_search" style="padding-top:3px" >
            	<form class="search-form" action="<?php echo $this->baseUrl("admin/tintuc/timkiem");?>" method="post">
					<input name="search-text" class="t" onfocus="if (this.value == 'Tìm kiếm …') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Tìm kiếm …';}" type="text" value="Tìm kiếm …"/>
					<input class="searchsubmit" type="submit" value="Tìm kiếm" style="cursor:pointer; height: 21px; padding-bottom:1px"/>
				</form>
            </div>
    </header>
	<div class="tab_container">
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=0;
								foreach ($this->list as $item)
								{?>
									{ news_title: '<?php echo $item['news_title'];?>', 
										news_avatar: '<?php echo $item['news_avatar'];?>',
										news_summary: '<?php $summ= str_replace(array("\n", "\r"), ' ', strip_tags($item['news_summary']));
														echo substr($summ, 0, 400);?>',   
										news_author: "<?php echo $item['news_author'];?>",
										news_modified_date: "<?php if ($item['news_modified_date']!='0000-00-00 00:00:00') echo $item['news_modified_date'];?>",
										news_status: "<?php echo $item['news_status'];?>",
										category_id: "<?php echo $this->categoriesid[$count]; ?>",
										is_hot : "<?php if($item['is_hot'] == "1") echo 'Có'; else echo 'Không'; ?>",
										optionedit: "<?php echo $item['news_id'];?>",
										optiondel: "<?php if ($item['news_author']!="") echo $item["news_id"]; else echo " ";?>"
									},
								<?php $count++;}?>
							];
				
				var count=1;
				var table = new Y.DataTable({
					columns: [{
								key: 'news_title',
								label: 'Tiêu đề',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true // Must be set or the html will be escaped
							},
							{
								key: 'news_avatar',
								label: 'Ảnh đại diện',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'news_summary',
								label: 'Tóm tắt',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'news_author',
								label: 'Tác giả',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'news_modified_date',
								label:'Ngày chính sửa',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'news_status',
								label:'Trạng thái',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'is_hot',
								label:'Tin hot',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'optiondel',
								label:'Xóa',
								formatter: '<a class="del_button" onclick="confirmDel({value})" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>',
								allowHTML: true
							},
							{
								key: 'optionedit',
								label:'Sửa',
								formatter: '<a href="<?php echo $this->baseUrl();?>/admin/tintuc/edit/newsid/{value}" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>',
								allowHTML: true
							}
							],
					data: data,
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
				<div class="submit_link" style="float:right">
					<a class="alt_btn" href="<?php echo $this->baseUrl('admin/tintuc/insert');?>">Thêm mới</a>
				</div>
				
				<div class="submit_link" style="float:left; font-weight: bold;">
					<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
				</div>
		</footer>
	</div>
</article>