<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
		function confirmDel(value)
				{
					var x;
					var r=confirm("Bạn muốn xóa tin tức này?");
					if (r==true)
					{
						var uri="<?php echo $this->baseUrl();?>/admin/tintuc/delete/newsid/"+value;
						window.location=uri;
					}
					else 
					{	
					}
				}
</script>
<style>
	.del_button{cursor:pointer}
</style>

<?php if (isset($_SESSION['result']))
{
	echo '<p class="message">';
	echo $_SESSION['result'];
	echo '</p>';
	unset($_SESSION['result']);
}
?>

<article class="module width_full">
	<header><h3><?php echo $this->title;?></h3></header>
	<div class="tab_container">
		<!-- div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0">
				<thead> 
					<tr> 
	    				<th>Tiêu đề</th> 
	    				<th>Tóm tắt</th> 
	    				<th style="min-width:70px">Tác giả</th>
	    				<th style="min-width:100px">Ngày chỉnh sửa</th>
	    				<th style="min-width:70px">Trạng thái</th>
	    				<th style="min-width:100px">Chuyên mục</th>
	    				<th style="min-width:70px">Tùy chọn</th>
					</tr> 
				</thead>
				<tbody>
				 	<?php 
				 	$count=0;
				 	foreach ($this->list as $item)
				 	{?>
				 		<tr> 
		    				<td><a href="<?php echo $this->baseUrl();?>/admin/tintuc/edit/newsid/<?php echo $item['news_id']?>"><?php echo $this->cutString($item['news_title'], 150);?></a></td> 
		    				<td><?php echo $this->cutString($item['news_summary'],150);?></td> 
		    				<td><?php echo $item['news_author'];?></td>
		    				<td><?php if ($item['news_modified_date']!='0000-00-00 00:00:00') echo $item['news_modified_date'];?></td>
		    				<td><?php echo $item['news_status'];?></td>
		    				<td>
		    					<?php 
		    						echo $this->categoriesid[$count];
		    					?>
		    				</td>
		    				<td>
		    					<a href="<?php echo $this->baseUrl();?>/admin/tintuc/edit/newsid/<?php echo $item['news_id']?>" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a>
		    					<a class="del_button" title="Del">
		    						<img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png">
		    						<input type="hidden" value="<?php echo $item['news_id']?>"/>
		    					</a>
		    				</td>
						</tr>
				 	<?php $count++;}?>
				</tbody>
			</table>
		</div -->
		
		<script src="http://yui.yahooapis.com/3.7.2/build/yui/yui-min.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			YUI().use('datatable', function (Y) {
				var data = [
								<?php 
								$count=0;
								foreach ($this->list as $item)
								{?>
									{ news_title: '<?php echo $item['news_title'];?>', 
										news_summary: '<?php echo $item['news_summary'];?>',   
										news_author: '<?php echo $item['news_author'];?>',
										news_modified_date: '<?php if ($item['news_modified_date']!='0000-00-00 00:00:00') echo $item['news_modified_date'];?>',
										news_status: '<?php echo $item['news_status'];?>',
										category_id: '<?php echo $this->categoriesid[$count]; ?>',
										option: '<?php echo $item['news_id']?>'
									},
								<?php $count++;}?>
							];
				
				var count=1;
				
				var table = new Y.DataTable({
					columns: [{
								key: 'news_title',
								label: 'Tiêu đề',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true // Must be set or the html will be escaped
							},
							{
								key: 'news_summary',
								label: 'Tóm tắt',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true 
							},
							{
								key: 'news_author',
								label: 'Tác giả',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'news_modified_date',
								label:'Ngày chính sửa',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'news_status',
								label:'Trạng thái',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'category_id',
								label:'Chuyên mục',
								sortable:true,
								formatter: '<span>{value}</span>',
								allowHTML: true
							},
							{
								key: 'option',
								label:'Tùy chọn',
								formatter: '<a href="<?php echo $this->baseUrl();?>/admin/tintuc/edit/newsid/{value}" title="Edit"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_edit.png"></a><a class="del_button" onclick="confirmDel({value})" title="Del"><img src="<?php echo $this->baseUrl();?>/application/templates/admin/images/icn_trash.png"></a>',
								allowHTML: true
							}],
					data: data,
	
					// and/or a summary (table attribute)
				});
	
				table.render("#listnews");
			});
		</script>
		<div class="yui3-skin-sam">
			<div class="example yui3-skin-sam" id="listnews">
			</div>
		</div>
		
		<footer>
			<div class="submit_link">
				<a class="alt_btn" style="float:right" href="<?php echo $this->baseUrl('admin/tintuc/insert');?>">Thêm mới</a>
				<?php echo $this->paginationControl($this->list,
                                    'Sliding',
                                    'tintuc/pagination.phtml');?>
			</div>
		</footer>
	</div>
</article>