<script src="<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/fckeditor.js" type="text/javascript"></script>
<script language='javascript' type='text/javascript' src='<?php echo $this->baseUrl();?>/application/templates/admin/js/customs.js'></script>

<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/jquery.ui.all.css">
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/jquery-1.8.0.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/ui/jquery.ui.datepicker.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/application/templates/admin/datepicker/themes/base/demos.css">
<script type="text/javascript">
	$(function() {
		$( ".datepicker" ).datepicker();
		setUpFCK('news_content',400,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
		setUpFCK('news_summary',200,'<?php echo $this->baseUrl();?>/application/templates/admin/js/fckeditor/');
	});
</script>

<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>
		
<form method="post" action="<?php echo $this->form->getAction();?>">
	<article class="module width_full">
		<header><h3><?php echo $this->title;?></h3></header>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<?php echo $this->error;?>
				<fieldset>
					<label>Tiêu đề</label>
					<?php echo $this->form->getElement('news_title');?>
				</fieldset>
				<fieldset>
					<label>Tóm tắt</label>
					<?php echo $this->form->getElement('news_summary');?>
				</fieldset>
				<fieldset>
					<label>Nội dung</label>
					<?php echo $this->form->getElement('news_content');?>
				</fieldset>
				<fieldset>
					<label>Tác giả</label>
					<?php echo $this->form->getElement('news_author');?>
				</fieldset>
				<fieldset>
					<label>Ngày đăng</label>
					<?php echo $this->form->getElement('news_post_date');?>
				</fieldset>
				<fieldset>
					<label>Ngày sửa</label>
					<?php echo $this->form->getElement('news_modified_date');?>
				</fieldset>
				<?php
					if($_SESSION['role_id'] == 0)
					{
				?>
				<fieldset>
					<label>Trạng thái</label>
					<?php echo $this->form->getElement('news_status');?>
				</fieldset>
				<?php
					}
				?>
				<fieldset>
					<label>Danh mục</label>
					<?php echo $this->form->getElement('category_id');?>
				</fieldset>
				<fieldset>
					<label>Tin hot</label>
					<?php echo $this->form->getElement('is_hot');?>
				</fieldset>
			</div>
		</div>
		<footer>
			<div class="submit_link">
				<input type="submit" name="submit" value="Thêm" class="alt_btn">
			</div>
		</footer>
	</article>
</form>