<?php if ($this->pageCount): ?>
<div class="paginationControl" align=center style="float:left; margin-left:25px">
	<style>
		.paginationControl{font-size:15px}
	</style>
<?php 
	if (isset($this->previous)){
  		echo '<a href="' . $this->url(array('page' => $this->previous)). '"> &lt; Previous</a>  ';
	}
	foreach ($this->pagesInRange as $page){
	   if ($page != $this->current){
	   		echo  '<a href="' . $this->url(array('page' => $page)). '">' . $page . '</a>  ';
	  }else{
	  	echo $page . '  ';
	  }
   }
	 if (isset($this->next)){
		echo '<a href="' . $this->url(array('page' => $this->next)) . '">Next &gt;</a>';
  	 }
  ?>
</div>
<?php endif; ?>
