        <div class="element_detail">
        	<div class="subpage_wapper_left_top_detail">
            	<?php echo $this->news['news_title']?>
            </div>
            <div class="subpage_new_detail">            
                	<ul>
                    	<li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/date.png"> <?php echo $this->news['news_post_date'] ?></li>
                        <li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/bl.png"> <?php echo count($this->listComment) ?> Bình luận</li>
                        <li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/print.png"> Bản in</li>
                        <li>Chia sẻ:
                        	<ul id="share">
                            	<li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/mail.png"></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/tt.png"></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/fb.png"></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/sb.png"></a></li>
                            </ul>
                        </li>
                    </ul>               
            </div>	
            <div id="content_detail">
               <div class="p_detail">
               		<?php echo strip_tags($this->news['news_summary']) ?>
               </div><br>
               <span>
               		<?php echo $this->news['news_content'] ?>
               </span>
           </div><br clear="both">
           </div>
           <div class="detail_add">
           
           </div>
           <div class="element_detail2">
           		<div style=" border-bottom:1px solid #e9e9e9">
                	<p class="p_detail">Ý kiến bạn đọc (<?php echo count($this->listComment) ?>)</p> 
                </div>
                <div style="border-bottom:1px solid #e9e9e9">
                	<p class="p_detail">Barney Simpler</p>
                    <p><?php echo $this->news['news_post_date'] ?></p>
                    <p>Vivamus a turpis justo, nec lobortis felis. Donec id diam enim euismod gravida. Sed non dui nec sapien mollis ornare.</p>
                    <p class="p_detail">Barney Simpler</p>
                    <p>08:00, 21/10/2012</p>
                    <p>Vivamus a turpis justo, nec lobortis felis. Donec id diam enim euismod gravida. Sed non dui nec sapien mollis ornare.</p><br>
                </div>
                <div>
                	<p class="p_detail">Ý kiến của bạn</p>
                    <form action="" method="">
                        <input name="name" class="n" onfocus="if (this.value == 'name') {this.value = '';}" onblur="if (this.value == '') {this.value = 'name';}" type="text" value="name"><br>
                        <input name="email" class="e" onfocus="if (this.value == 'email') {this.value = '';}" onblur="if (this.value == '') {this.value = 'email';}" type="text" value="email"><br>
                         <input name="message" class="m" onfocus="if (this.value == 'message') {this.value = '';}" onblur="if (this.value == '') {this.value = 'message';}" type="text" value="message"><br>
                         <input type="submit" class="submit_detail" value="submit" style="cursor:pointer">
                    </form>
                </div>
           </div>
           <div class="detail_ul">
           	  <ul>
           	  	<?php
           	  	if(count($this->listNewestNews) > 0)
				{
					foreach($this->listNewestNews as $news)
					{
						?>
							<li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title'] ?></a></li>
						<?php
					}
				}
           	  	?>
              </ul>
           </div>
