<div style="display: block" id="sendemailstatus">
	
</div>

<style>
	.errors{list-style-type:none; color: red; padding:10px}
</style>        
        <div class="element_detail">
        	<div class="subpage_wapper_left_top_detail">
            	<?php echo $this->news['news_title']?>
            </div>
            <div class="subpage_new_detail">            
                	<ul>
                    	<li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/date.png"> <?php echo $this->news['news_post_date'] ?></li>
                        <li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/bl.png"> <?php echo count($this->listComment) ?> Bình luận</li>
                        <li><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/print.png"> Bản in</li>
                        <li>Chia sẻ:
                        	<ul id="share">
                            	<li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/mail.png"></a></li>
                                <li><a href="https://twitter.com/share" ><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/tt.png"></a>
								<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
								</li>
                                <li><a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->baseUrl()?>/tin-tuc/chi-tiet/<?php echo $this->news['news_id']?>-<?php echo $this->news['alias'];?>.html"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/fb.png"></a></li>
                                <li><a href="#"><img src="<?php echo $this->baseUrl()?>/application/templates/front/images/sb.png"></a></li>
                            </ul>
                        </li>
                    </ul>               
            </div>	
            <div id="content_detail">
               <div class="p_detail">
               		<?php echo strip_tags($this->news['news_summary']) ?>
               </div><br>
               <span>
               		<?php echo $this->news['news_content'] ?>
               </span>
           </div><br clear="both">
           </div>
           <div class="detail_add">
	           	<a href="<?php echo $this->listquangcao2['ads_link']; ?>" target="_blank">
		            <?php
		            	echo $this->listquangcao2['ads_banner']; 
		            ?>
		        </a>
           </div>
           <div class="element_detail2">
           		<div style="border-bottom:1px solid #e9e9e9">
                	<p class="p_detail">Ý kiến bạn đọc (<?php echo count($this->listComment) ?>)</p> 
                </div>
                
                	<?php
                	if(count($this->listComment) > 0)
					{
						?>
							<div style="border-bottom:1px solid #e9e9e9;height:200px;overflow: auto">
						<?php
						foreach($this->listComment as $comment)
						{
							?>
								<p class="p_detail"><?php echo $comment['comment_name'] ?></p>
			                    <p><?php echo $comment['comment_time'] ?></p>
			                    <p><?php echo $comment['comment_content'] ?></p>
							<?php
						}
					}
					else {
						?>
							<div style="border-bottom:1px solid #e9e9e9;">
								Tin bài này chưa có bình luận nào
						<?php
					}
                	?>
                	</div>
                <div>
                	<p class="p_detail">Ý kiến của bạn</p>
                    <form action="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $this->news['news_id'] ?>-<?php echo $this->news['alias'] ?>.html" method="post">
                         <?php 
                         	echo $this->form->getElement('comment_name');
							echo $this->form->getElement('comment_email');
							echo $this->form->getElement('comment_content');
							echo $this->form->getElement('comment_captcha');
                         ?>
                         <br/>
                         <input type="submit" class="submit_detail" value="Gửi bình luận" style="cursor:pointer">
                    </form>
                </div>
           </div>
           <div class="detail_ul">
           	  <ul>
           	  	<?php
           	  	if(count($this->listNewestNews) > 0)
				{
					foreach($this->listNewestNews as $news)
					{
						?>
							<li><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title'] ?></a></li>
						<?php
					}
				}
           	  	?>
              </ul>
           </div>
<!-------------- Start Script Area ------------>
<script>
	function formSendMail() {
		var x;
		var email=prompt("Nhập email mà bạn muốn chia sẻ trang web này","someone@example.com");
		var url = document.URL;
		if (email!=null) {
			$('#sendemailstatus').load('<?php echo $this->baseUrl('/dataajax/sendmail/format/html?email=')?>'+email+"&url="+url);
		} else {
			alert("Bạn phải nhập một email"); 
		}
	}
</script>
<!-------------- End Script Area ------------>