<style>
	#slide{display:none}
</style>

<script style="text/javascript">
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=116608581828346";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="detail">
	<h4 style="display:inline"><a href="<?php echo $this->baseUrl(); ?>">Trang chủ</a> >> 
		<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $this->parent['category_id']; ?>-1-<?php if(isset($this->parent['alias'])) echo $this->parent['alias']; ?>.html"><?php echo $this->parent['category_name']; ?></a> >> 
		<h3 style="display:inline;">
			<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chuyen-muc/<?php echo $this->child['category_id']; ?>-<?php echo $this->child['alias']; ?>.html"><?php echo $this->child['category_name']; ?></a>
		</h3>
	</h4>
	<h2 style="color:#07506b;margin-left:10px"><?php echo $this->news['news_title']; ?></h2>
	<h4 style="margin-left: 10px;margin-top: -8px;margin-bottom:0px;color:#323232; font-weight:normal; font-style:italic">Ngày đăng: <?php echo $this->news['news_post_date']; ?></h4>
	<p style="margin-left:10px"><?php echo $this->news['news_content']; ?></p>
	<div id="fb-root"></div>
	<div class="fb-like" data-href="http://www.niwvietnam.info/unc/" data-send="true" data-width="450" data-show-faces="true"></div>
	<hr/>
	<?php
	if(isset($_SESSION['logged']))
	{
		?>
			<h3>Bạn đang đăng nhập bằng tài khoản <span style="color:red"><?php echo $_SESSION['logged']; ?></span>&nbsp;&nbsp;&nbsp;
			<a style="text-decoration: none" href="<?php echo $this->baseUrl(); ?>/tintuc/logout"><i>Thoát</i></a></h3>
			<form method="post" action="<?php echo $this->baseUrl();?>/tintuc/addcomment/newsid/<?php echo $this->news['news_id']; ?>/readerid/<?php echo $_SESSION['reader_id']; ?>">
				<div id="addComment">
					<textarea name="comment_content" style="width:100%" rows="5"></textarea>
					<input type="submit" name="submit" value="Gửi bình luận"/>
				</div>
				<?php
				if(isset($_SESSION['fail'])) 
				{
					?>
						<h3><i style="color:red"><?php echo $_SESSION['fail'];unset($_SESSION['fail']);?></i></h3>
					<?php
				}
				?>
			</form>
				
		<?php
	}
	else 
	{
		?>
			<form method="post" action="<?php echo $this->baseUrl(); ?>/tintuc/login/newsid/<?php echo $this->news['news_id']; ?>">
				<div id="login">
					<h3>Đăng nhập bằng tài khoản forum UNC để bình luận về tin tức này</h3>
					<hr/>
					<table>
						<tr>
							<td>Tên đăng nhập : </td>
							<td><?php echo $this->form->getElement('user_name'); ?></td>
						</tr>
						<tr>
							<td>Mật khẩu : </td>
							<td><?php echo $this->form->getElement('pass_word'); ?></td>
						</tr>
					</table>
					<input style="margin-left:20%" type="submit" name="submit" value="Đăng nhập"/>
				</div>
				<?php
				if(isset($_SESSION['fail'])) 
				{
					?>
						<h3><i style="color:red"><?php echo $_SESSION['fail'];unset($_SESSION['fail']);?></i></h3>
					<?php
				}
				?>
			</form>
		<?php
	}
	?>	
	
	<div id="comment">
		<hr/>
		<h3>Danh sách bình luận</h3>
		<hr/>
		<?php 
		$count = 0;
		if(count($this->listComment) > 0)
		{
			foreach($this->listComment as $comment)
			{
				if($this->listImage[$count] == 0)
				{
				?>
					<img alt="" src="http://1.gravatar.com/avatar/b0eb17f97a5c244abfd54d0192e00a4d?s=68&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D68&amp;r=G" class="avatar avatar-68 photo" height="68" width="68">
				<?php 
				}
				else
				{
					?>
						<img alt="" src="<?php echo $this->baseUrl(); ?>/forum/image.php?u=1&dateline=<?php echo $this->listImage[$count]; ?>" class="avatar avatar-68 photo" height="68" width="68">
					<?php
				}
				
				?>
				<div style="#373737;background-color:#E4E4E4;margin-left:80px;margin-top:-67px;border-radius: 5px;border: 1px solid #ddd;padding: 10px;width:85%">
					<div style="margin-left:10px">
						<span style="color:blue;"><?php echo $this->listUser[$count]['username'] ?></span>   :   <span><?php echo $comment['comment_time']; ?></span> đã bình luận :
					</div>
					<div style="margin:20px">
						<?php echo $comment['comment_content']; ?>
					</div>
				</div>
				<br style="clear:both">
			<?php 
				$count++;
			}
		}
		else 
		{
			echo 'Tin bài này chưa có bình luận nào';
		}
		?>
	</div>
	
	<div style="margin-top:10px;margin-left:0px;border: 1px solid;border-radius: 5px;background-color:#F8F8F8;width:100%">
		<div style="padding-left:10px">
			<h3>Các tin mới đăng</h3>
			<hr/>
			<ul class="listNewest" style="list-style-type: none">
				<?php if(isset($this->listNewestNews))
				{
					foreach($this->listNewestNews as $news)
					{
				?>
                 <li>
                  	<img src="/unc/application/templates/front/images/sao.png">
					<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']; ?>.html">
					 	<?php echo $news['news_title']; ?>											
					</a>
				</li>
				<?php
				}}
				?>
             </ul>
		</div>
	</div><br/>
	
	<div style="margin-top:10px;margin-left:0px;border: 1px solid;border-radius: 5px;background-color:#F8F8F8;width:100%">
		<div style="padding-left:10px">
			<h3>Các tin đã đăng</h3>
			<hr/>
			<ul class="listNewest" style="list-style-type: none">
                <?php if(isset($this->listNewsPosted))
				{
					foreach($this->listNewsPosted as $news)
					{
				?>
                 <li>
                  	<img src="/unc/application/templates/front/images/sao.png">
					<a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias']; ?>.html">
					 	<?php echo $news['news_title']; ?>											
					</a>
				</li>
				<?php
				}}
				?>
             </ul>
		</div>
	</div>
</div>