		<div class="element_detail">
			<div class="children_down-title"><a href="#">Văn miếu</a></div>
        	<div class="subpage_wapper_left_top">
            	<div class="children_down2"><a href="#">Danh nhân văn hóa</a></div><div class="children_down">|</div>
                <div class="children_down2"><a href="#">Thiên cổ hùng văn</a></div><div class="children_down">|</div>
                <div class="children_down2"><a href="#">Tác phẩm đương đại</a></div><div class="children_down">|</div>
                <div class="children_down2"><a href="#">Văn đàn</a></div>
            </div>
            <?php 
            	if(count($this->list) > 0)
				{
					foreach($this->list as $news)
					{
            ?>
            <div class="subpage_new">
            	<div class="img_new">
            		<?php
            			if($news['news_avatar'] != "")
						{
							$str = $news['news_avatar'];
							$preg1 = preg_match_all('#<img.*>#',$str,$match);
							echo $match[0][0];
						}
						else {
							?>
								<img src="<?php echo $this->baseUrl()?>/application/templates/front/images/new.gif">
							<?php
						}
            		?>
                </div>
                <div class="text_new">
                	<a class="a-title" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title'] ?></a>
                    <p class="date"><?php echo $news['news_post_date'] ?></p>
                    <p class="text"><?php echo strip_tags($news['news_summary'])?></p>
                </div>
            </div><br/>
           <?php
					}
				}
				else {
					echo 'Chuyên mục này chưa có tin bài nào';
				}
           ?>
           <div class="page_video" style="margin-left:15px;">
				<ul id="page_video">
					<li style=" margin-right:30px"><a href="#">Trang</a></li><li>  </li>
					<li><a href="#">1</a></li><li>|</li>
					<li><a href="#">2</a></li><li>|</li>
					<li><a href="#">....</a></li><li>|</li>
					<li><a href="#">10</a></li>
				</ul>
			</div> <br clear="both">
			</div>
			<div class="detail_add"></div>
