<div style="margin-top:10px">
	<?php 
	if(count($this->list) > 0)
	{
		foreach($this->list as $news)
		{
	?>
		<div style="margin-top:10px">
	 			<?php
	 				$str = $news['news_summary'];
					$preg = preg_match_all('#<img.*/>#',$str,$match);
					if($preg > 0)
					{
						?>
							<a style="color:blue;" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>">
						<?php
						echo $match[0][0].'</a>';
					} 
					else 
					{
						?>
							<a style="color:blue;" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>">
								<img class="img130" src="http://dantri21.vcmedia.vn/zoom/130_100/I3KdHJtU0B3ELPKGaTLe/Image/2012/10/bovien-97975.jpg" alt="Hãi hùng bò viên">
							</a>
						<?php
					}
	 			?>
	 		
	 		<div>
	  			<h3 style="color:blue;margin-left:145px;margin-top:-92px"><a href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html" title="<?php echo $news['news_title']; ?>"><?php echo $news['news_title']; ?></a></h3>
	  			<div style="margin-left:145px">
	  				<?php
	  				 	$str = $news['news_summary']; 
						
						$preg1 = preg_match_all('#<img.*/>#',$str,$match);
						if($preg1 > 0)
						{
							$str = str_replace($match[0][0],"", $str);
						}
						
						$preg2 = preg_match('#<br>.*</a>#',$str,$match);
						if($preg2 > 0)
						{
							$str = str_replace($match[0],"", $str);
						}
						
						echo $str;						
						
	  				?>
	  			</div>
	  			
	  			<a style="float:right" href="<?php echo $this->baseUrl(); ?>/tin-tuc/chi-tiet/<?php echo $news['news_id']; ?>-<?php echo $news['alias'];?>.html">Xem tiếp</a>
	 		</div>
	 	</div>
	 	<br style="clear:both">
	 	
 	<?php
		}
	}
	else 
	{
	?>
		<h3 style="margin:10px;color:red"><i>Chuyên mục này chưa có tin bài nào</i></h3>
	<?php
	}
 	?>
</div>
<div style="margin-top:40px;float:right">
<?php echo $this->paginationControl($this->list,'Sliding','tintuc/pagination.phtml');?>
</div>