<div style="border-bottom:1px solid #e9e9e9">
                	<p class="p_detail">Ý kiến bạn đọc (<?php echo $this->amount ?>)</p> 
                </div>
<?php if(count($this->listComment) > 0) { ?>
						<div style="border-bottom:1px solid #e9e9e9">
							<?php foreach($this->listComment as $comment) { ?>
									<p class="p_detail"><?php echo $comment['comment_name'] ?></p>
				                    <p><?php echo $comment['comment_time'] ?></p>
				                    <p><?php echo $comment['comment_content'] ?></p>
				                    <div class="thich-button">
				                    	<p style="text-align:right">
				                    		<?php 
				                    		if (isset($_SESSION['liked']))
				                    		{
				                    			echo $_SESSION['liked']; die();
				                    			if (strpos($_SESSION['liked'], ','.$comment['comment_id'].',')!==false)
				                    			{?>
				                    				<a>Thích</a>
				                    			<?php }
				                    			else {?>
				                    				<a class="click" href="<?php echo $this->baseUrl();?>/tintuc/like/comment_id/<?php echo $comment['comment_id']?>">Thích</a>
				                    			<?php }
			                    			}
			                    			else {?>
			                    				<a class="click" href="<?php echo $this->baseUrl();?>/tintuc/like/comment_id/<?php echo $comment['comment_id']?>">Thích</a>
			                    			<?php }?>
				                    		<span> (<?php echo $comment['like'] ?>)</span>
			                    		</p>
				                    </div>
				            <?php } ?>
						</div>
						<div>
							<?php echo $this->paginationControl($this->listComment,'Sliding','tintuc/pagination.phtml');?>
						</div>
					<?php }
					else {
						?>
							<div style="border-bottom:1px solid #e9e9e9;">
								Tin bài này chưa có bình luận nào
							</div>								
						<?php
					}
                	?>
<script type="text/javascript">
		var root="http://localhost";
		$(".paginationControl .number-bt").click(function(){
			var page= parseInt($(this).text());
			$("#comment-panel").load(root+"<?php echo $this->baseUrl();?>/tintuc/loadcomment/newsid/<?php echo $this->news_id?>/page/"+page);
			return false;
		});
		$(".paginationControl .next-bt, .paginationControl .prev-bt").click(function(){
			var url= $(this).attr('href');
			var segments=url.split('/');
			var page=segments[segments.length-1];
			$("#comment-panel").load(root+"<?php echo $this->baseUrl();?>/tintuc/loadcomment/newsid/<?php echo $this->news_id?>/page/"+page);
			return false;
		})
		
		//like===========
		$(".thich-button .click").click(function(){
			var href=$(this).attr('href');
			var segment=href.split('/');
			var id=segment[segment.length-1];

			$(this).parent().parent().load(root+"<?php echo $this->baseUrl();?>/tintuc/like/comment_id/"+id);
			return false;
		});
</script>                	